<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Crypt;
use Illuminate\Support\Facades\Hash;
use App\Models\CodiceCer;


class CodiceCerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
		Model::unguard();

		$values = array(
["000000","I rifiuti contrassegnati nell'elenco in rosso con un asterisco '*' sono rifiuti pericolosi ai sensi della direttiva 2008/98/CE relativa ai rifiuti pericolosi"],
["010000","RIFIUTI DERIVANTI DA PROSPEZIONE, ESTRAZIONE DA MINIERA O CAVA, NONCHÉ DAL TRATTAMENTO FISICO O CHIMICO DI MINERALI"],
["010100","Rifiuti prodotti dall'estrazione di minerali"],
["010101","rifiuti da estrazione di minerali metalliferi"],
["010102","rifiuti da estrazione di minerali non metalliferi"],
["010300","rifiuti prodotti da trattamenti chimici e fisici di minerali metalliferi"],
["010304","*sterili che possono generare acido prodotti dalla lavorazione di minerale solforoso"],
["010305","*altri sterili contenenti sostanze pericolose"],
["010306","sterili diversi da quelli di cui alle voci 01 03 04 e 01 03 05"],
["010307","*altri rifiuti contenenti sostanze pericolose prodotti da trattamenti chimici e fisici di minerali metalliferi"],
["010308","polveri e residui affini diversi da quelli di cui alla voce 01 03 07"],
["010309","fanghi rossi derivanti dalla produzione di allumina, diversi da quelli di cui alla voce 01 03 10"],
["010310","*fanghi rossi derivanti dalla produzione di allumina contenenti sostanze pericolose, diversi da quelli di cui alla voce 01 03 07. (nuovo codice CER)"],
["010399","rifiuti non specificati altrimenti"],
["010400","rifiuti prodotti da trattamenti chimici e fisici di minerali non metalliferi"],
["010407","*rifiuti contenenti sostanze pericolose, prodotti da trattamenti chimici e fisici di minerali non metalliferi"],
["010408","scarti di ghiaia e pietrisco, diversi da quelli di cui alla voce 01 04 07"],
["010409","scarti di sabbia e argilla"],
["010410","polveri e residui affini, diversi da quelli di cui alla voce 01 04 07"],
["010411","rifiuti della lavorazione di potassa e salgemma, diversi da quelli di cui alla voce 01 04 07"],
["010412","sterili ed altri residui del lavaggio e della pulitura di minerali, diversi da quelli di cui alle voci 01 04 07 e 01 04 11"],
["010413","rifiuti prodotti dal taglio e dalla segagione della pietra, diversi da quelli di cui alla voce 01 04 07"],
["010499","rifiuti non specificati altrimenti"],
["010500","fanghi di perforazione ed altri rifiuti di perforazione"],
["010504","fanghi e rifiuti di perforazione di pozzi per acque dolci"],
["010505","*fanghi e rifiuti di perforazione contenenti oli"],
["010506","*fanghi di perforazione ed altri rifiuti di perforazione contenenti sostanze pericolose"],
["010507","fanghi e rifiuti di perforazione contenenti barite, diversi da quelli delle voci 01 05 05 e 01 05 06"],
["010508","fanghi e rifiuti di perforazione contenenti cloruri, diversi da quelli delle voci 01 05 05 e 01 05 06"],
["010599","rifiuti non specificati altrimenti"],
["020000","RIFIUTI PRODOTTI DA AGRICOLTURA, ORTICOLTURA, ACQUACOLTURA, SELVICOLTURA, CACCIA E PESCA, TRATTAMENTO E PREPARAZIONE DI ALIMENTI"],
["020100","rifiuti prodotti da agricoltura, orticoltura, acquacoltura, selvicoltura, caccia e pesca"],
["020101","fanghi da operazioni di lavaggio e pulizia"],
["020102","scarti di tessuti animali"],
["020103","scarti di tessuti vegetali"],
["020104","rifiuti plastici (ad esclusione degli imballaggi)"],
["020105","rifiuti agrochimici"],
["020106","feci animali, urine e letame (comprese le lettiere usate), effluenti, raccolti separatamente e trattati fuori sito"],
["020107","rifiuti della silvicoltura"],
["020108","*rifiuti agrochimici contenenti sostanze pericolose"],
["020109","rifiuti agrochimici diversi da quelli della voce 02 01 08"],
["020199","rifiuti non specificati altrimenti"],
["020200","rifiuti della preparazione e del trattamento di carne, pesce ed altri alimenti di origine animale"],
["020201","fanghi da operazioni di lavaggio e pulizia"],
["020202","scarti di tessuti animali"],
["020203","scarti inutilizzabili per il consumo o la trasformazion"],
["020204","fanghi prodotti dal trattamento in loco degli effluenti"],
["020299","rifiuti non specificati altrimenti"],
["020300","rifiuti della preparazione e del trattamento di frutta, verdura, cereali, oli alimentari, cacao, caffè, tè e tabacco; della produzione di conserve alimentari; della produzione di lievito ed estratto di lievito; della preparazione e fermentazione di melassa"],
["020301","fanghi prodotti da operazioni di lavaggio, pulizia, sbucciatura, centrifugazione e separazione di componenti"],
["020302","rifiuti legati all'impiego di conservanti"],
["020303","rifiuti prodotti dall'estrazione tramite solvente"],
["020304","scarti inutilizzabili per il consumo o la trasformazione"],
["020305","fanghi prodotti dal trattamento in loco degli effluenti"],
["020399","rifiuti non specificati altrimenti"],
["020400","rifiuti prodotti dalla raffinazione dello zucchero"],
["020401","terriccio residuo delle operazioni di pulizia e lavaggio delle barbabietole"],
["020402","carbonato di calcio fuori specifica"],
["020403","fanghi prodotti dal trattamento in loco degli effluenti"],
["020499","rifiuti non specificati altrimenti"],
["020500","rifiuti dell'industria lattiero-casearia"],
["020501","scarti inutilizzabili per il consumo o la trasformazione"],
["020502","fanghi prodotti dal trattamento in loco degli effluenti"],
["020599","rifiuti non specificati altrimenti"],
["020600","rifiuti dell'industria dolciaria e della panificazione"],
["020601","scarti inutilizzabili per il consumo o la trasformazione"],
["020602","rifiuti legati all'impiego di conservanti"],
["020603","fanghi prodotti dal trattamento in loco degli effluenti"],
["020699","rifiuti non specificati altrimenti"],
["020700","rifiuti della produzione di bevande alcoliche ed analcoliche (tranne caffè, tè e cacao)"],
["020701","rifiuti prodotti dalle operazioni di lavaggio, pulizia e macinazione della materia prima"],
["020702","rifiuti prodotti dalla distillazione di bevande alcoliche"],
["020703","rifiuti prodotti dai trattamenti chimici"],
["020704","scarti inutilizzabili per il consumo o la trasformazione"],
["020705","fanghi prodotti dal trattamento in loco degli effluenti"],
["020799","rifiuti non specificati altrimenti"],
["030000","RIFIUTI DELLA LAVORAZIONE DEL LEGNO E DELLA PRODUZIONE DI PANNELLI, MOBILI, POLPA, CARTA E CARTONE"],
["030100","rifiuti della lavorazione del legno e della produzione di pannelli e mobili"],
["030101","scarti di corteccia e sughero"],
["030104","*segatura, trucioli, residui di taglio, legno, pannelli di truciolare e piallacci contenenti sostanze pericolose"],
["030105","segatura, trucioli, residui di taglio, legno, pannelli di truciolare e piallacci diversi da quelli di cui alla voce 03 01 04"],
["030199","rifiuti non specificati altrimenti"],
["030200 ","rifiuti dei trattamenti conservativi del legno"],
["030201","*prodotti per i trattamenti conservativi del legno contenenti composti organici non alogenati"],
["030202","*prodotti per i trattamenti conservativi del legno contenenti composti organici clorurati"],
["030203","*prodotti per i trattamenti conservativi del legno contenenti composti organometallici"],
["030204","*prodotti per i trattamenti conservativi del legno contenenti composti inorganici"],
["030205","*altri prodotti per i trattamenti conservativi del legno contenenti sostanze pericolose"],
["030299","prodotti per i trattamenti conservativi del legno non specificati altrimenti"],
["030300","rifiuti della produzione e della lavorazione di polpa, carta e cartone"],
["030301","scarti di corteccia e legno"],
["030302","fanghi di recupero dei bagni di macerazione (green liquor)"],
["030305","fanghi prodotti dai processi di disinchiostrazione nel riciclaggio della carta"],
["030307","scarti della separazione meccanica nella produzione di polpa da rifiuti di carta e cartone"],
["030308","scarti della selezione di carta e cartone destinati ad essere riciclati"],
["030309","fanghi di scarto contenenti carbonato di calcio"],
["030310","scarti di fibre e fanghi contenenti fibre, riempitivi e prodotti di rivestimento generati dai processi di separazione meccanica"],
["030311","fanghi prodotti dal trattamento in loco degli effluenti, diversi da quelli di cui alla voce 03 03 10"],
["030399","rifiuti non specificati altrimenti"],
["040000","RIFIUTI DELLA LAVORAZIONE DI PELLI E PELLICCE, NONCHÉ DELL'INDUSTRIA TESSILE"],
["040100","rifiuti della lavorazione di pelli e pellicce"],
["040101","carniccio e frammenti di calce"],
["040102","rifiuti di calcinazione"],
["040103","*bagni di sgrassatura esauriti contenenti solventi senza fase liquida"],
["040104","liquido di concia contenente cromo"],
["040105","liquido di concia non contenente cromo"],
["040106","fanghi, prodotti in particolare dal trattamento in loco degli effluenti, contenenti cromo"],
["040107","fanghi, prodotti in particolare dal trattamento in loco degli effluenti, non contenenti cromo"],
["040108","cuoio conciato (scarti, cascami, ritagli, polveri di lucidatura) contenenti cromo"],
["040109","rifiuti delle operazioni di confezionamento e finitura"],
["040199","rifiuti non specificati altrimenti"],
["010200 ","rifiuti dell'industria tessile"],
["040209","rifiuti da materiali compositi (fibre impregnate, elastomeri, plastomeri)"],
["040210","materiale organico proveniente da prodotti naturali (ad es. grasso, cera)"],
["040214","*rifiuti provenienti da operazioni di finitura, contenenti solventi organici"],
["040215","rifiuti da operazioni di finitura, diversi da quelli di cui alla voce 04 02 14"],
["040216","*tinture e pigmenti, contenenti sostanze pericolose"],
["040217","tinture e pigmenti, diversi da quelli di cui alla voce 04 02 16"],
["040219","*fanghi prodotti dal trattamento in loco degli effluenti, contenenti sostanze pericolose"],
["040220","fanghi prodotti dal trattamento in loco degli effluenti, diversi da quelli di cui alla voce 04 02 19"],
["040221","rifiuti da fibre tessili grezze"],
["040222","rifiuti da fibre tessili lavorate"],
["040299","rifiuti non specificati altrimenti"],
["050000","RIFIUTI DELLA RAFFINAZIONE DEL PETROLIO, PURIFICAZIONE DEL GAS NATURALE E TRATTAMENTO PIROLITICO DEL CARBONE"],
["050100","rifiuti della raffinazione del petrolio"],
["050102","*fanghi da processi di dissalazione"],
["050103","*morchie depositate sul fondo dei serbatoi"],
["050104","*fanghi acidi prodotti da processi di alchilazione"],
["050105","*perdite di olio"],
["050106","*fanghi oleosi prodotti dalla manutenzione di impianti e apparecchiature"],
["050107","*catrami acidi"],
["050108","*altri catrami"],
["050109","*fanghi prodotti dal trattamento in loco degli effluenti, contenenti sostanze pericolose"],
["050110","fanghi prodotti dal trattamento in loco degli effluenti, diversi da quelli di cui alla voce 05 01 09"],
["050111","*rifiuti prodotti dalla purificazione di carburanti tramite basi"],
["050112","*acidi contenenti oli"],
["050113","fanghi residui dell'acqua di alimentazione delle caldaie"],
["050114","rifiuti prodotti dalle torri di raffreddamento"],
["050115","*filtri di argilla esauriti"],
["050116","rifiuti contenenti zolfo prodotti dalla desolforizzazione del petrolio"],
["050117","bitumi"],
["050199","rifiuti non specificati altrimenti"],
["050600","rifiuti prodotti dal trattamento pirolitico del carbone"],
["050601","*catrami acidi"],
["050603","*altri catrami"],
["050604","rifiuti prodotti dalle torri di raffreddamento"],
["050699","rifiuti non specificati altrimenti"],
["050700","rifiuti prodotti dalla purificazione e dal trasporto di gas naturale"],
["050701","*rifiuti contenenti mercurio"],
["050702","rifiuti contenenti zolfo"],
["050799","rifiuti non specificati altrimenti"],
["060000","RIFIUTI DEI PROCESSI CHIMICI INORGANICI"],
["060100","rifiuti della produzione, formulazione, fornitura ed uso di acidi"],
["060101","*acido solforico ed acido solforoso"],
["060102","*acido cloridrico"],
["060103","*acido fluoridrico"],
["060104","*acido fosforico e fosforoso"],
["060105","*acido nitrico e acido nitroso"],
["060106","*altri acidi"],
["060199","rifiuti non specificati altrimenti"],
["060200","rifiuti della produzione, formulazione, fornitura ed uso di basi"],
["060201","*idrossido di calcio"],
["060203","*idrossido di ammonio"],
["060204","*idrossido di sodio e di potassio"],
["060205","*altre basi"],
["060299","rifiuti non specificati altrimenti"],
["060300","rifiuti della produzione, formulazione, fornitura ed uso di sali, loro soluzioni e ossidi metallici"],
["060311","*sali e loro soluzioni, contenenti cianuri"],
["060313","*sali e loro soluzioni, contenenti metalli pesanti"],
["060314","sali e loro soluzioni, diversi da quelli di cui alle voci 06 03 11 e 06 03 13"],
["060315","*ossidi metallici contenenti metalli pesanti"],
["060316","ossidi metallici, diversi da quelli di cui alla voce 06 03 15"],
["060399","rifiuti non specificati altrimenti"],
["060400","rifiuti contenenti metalli, diversi da quelli di cui alla voce 06 03"],
["060403","*rifiuti contenenti arsenico"],
["060404","*rifiuti contenenti mercurio"],
["060405","*rifiuti contenenti altri metalli pesanti"],
["060499","rifiuti non specificati altrimenti"],
["060500","fanghi prodotti dal trattamento in loco degli effluenti"],
["060502","*fanghi prodotti dal trattamento in loco degli effluenti, contenenti sostanze pericolose"],
["060503","fanghi prodotti dal trattamento in loco degli effluenti, diversi da quelli di cui alla voce 06 05 02"],
["060600","rifiuti della produzione, formulazione, fornitura ed uso di prodotti chimici contenenti zolfo, dei processi chimici dello zolfo e dei processi di desolforazione"],
["060602","*rifiuti contenenti solfuri pericolosi"],
["060603","rifiuti contenenti solfuri, diversi da quelli di cui alla voce 06 06 02"],
["060699","rifiuti non specificati altrimenti"],
["060700","rifiuti della produzione, formulazione, fornitura ed uso di prodotti alogeni e dei processi chimici degli alogeni"],
["060701","*rifiuti dei processi elettrolitici, contenenti amianto"],
["060702","*carbone attivato dalla produzione di cloro"],
["060703","*fanghi di solfati di bario, contenenti mercurio"],
["060704","*soluzioni ed acidi, ad es. acido di contatto"],
["060799","rifiuti non specificati altrimenti"],
["060800","rifiuti della produzione, formulazione, fornitura ed uso del silicio e dei suoi derivati"],
["060802","*rifiuti contenenti clorosilano"],
["060899","rifiuti non specificati altrimenti"],
["060900","rifiuti della produzione, formulazione, fornitura ed uso di prodotti fosforosi e dei processi chimici del fosforo"],
["060902","scorie fosforose"],
["060903","*rifiuti prodotti da reazioni a base di calcio contenenti o contaminati da sostanze pericolose"],
["060904","rifiuti prodotti da reazioni a base di calcio, diversi da quelli di cui alla voce 06 09 03"],
["060999","rifiuti non specificati altrimenti"],
["061000","rifiuti della produzione, formulazione, fornitura ed uso di prodotti chimici contenenti azoto, dei processi chimici dell'azoto e della produzione di fertilizzanti"],
["061002","*rifiuti contenenti sostanze pericolose"],
["061099","rifiuti non specificati altrimenti"],
["061100","rifiuti dalla produzione di pigmenti inorganici ed opacificanti"],
["061101","rifiuti prodotti da reazioni a base di calcio nella produzione di diossido di titanio"],
["061199","rifiuti non specificati altrimenti"],
["061300","rifiuti di processi chimici inorganici non specificati altrimenti"],
["061301","*prodotti fitosanitari, agenti conservativi del legno ed altri biocidi inorganici"],
["061302","*carbone attivato esaurito (tranne 06 07 02)"],
["061303","nerofumo"],
["061304","*rifiuti della lavorazione dell'amianto"],
["061305","*fuliggine"],
["061399","rifiuti non specificati altrimenti"],
["070000","RIFIUTI DEI PROCESSI CHIMICI ORGANICI"],
["070100","rifiuti della produzione, formulazione, fornitura ed uso di prodotti chimici organici di base"],
["070101","*soluzioni acquose di lavaggio ed acque madri"],
["070103","*solventi organici alogenati, soluzioni di lavaggio ed acque madri"],
["070104","*altri solventi organici, soluzioni di lavaggio ed acque madri"],
["070107","*fondi e residui di reazione, alogenati"],
["070108","*altri fondi e residui di reazione"],
["070109","*residui di filtrazione e assorbenti esauriti, alogenati"],
["070110","*altri residui di filtrazione e assorbenti esauriti"],
["070111","*fanghi prodotti dal trattamento in loco degli effluenti, contenenti sostanze pericolose"],
["070112","fanghi prodotti dal trattamento in loco degli effluenti, diversi da quelli di cui alla voce 07 01 11"],
["070199","rifiuti non specificati altrimenti"],
["070200","rifiuti della produzione, formulazione, fornitura ed uso (PFFU) di plastiche, gomme sintetiche e fibre artificiali"],
["070201","*soluzioni acquose di lavaggio ed acque madri"],
["070203","*solventi organici alogenati, soluzioni di lavaggio ed acque madri"],
["070204","*altri solventi organici, soluzioni di lavaggio ed acque madri"],
["070207","*fondi e residui di reazione, alogenati"],
["070208","*altri fondi e residui di reazione"],
["070209","*residui di filtrazione e assorbenti esauriti, alogenati"],
["070210","*altri residui di filtrazione e assorbenti esauriti"],
["070211","*fanghi prodotti dal trattamento in loco degli effluenti, contenenti sostanze pericolose"],
["070212","fanghi prodotti dal trattamento in loco degli effluenti, diversi da quelli di cui alla voce 07 02 11"],
["070213","rifiuti plastici"],
["070214","*rifiuti prodotti da additivi, contenenti sostanze pericolose"],
["070215","rifiuti prodotti da additivi, diversi da quelli di cui alla voce 07 02 14"],
["070216","*rifiuti contenenti silicone pericoloso"],
["070217","rifiuti contenenti siliconi diversi da quelli di cui alla voce 07 02 16"],
["070299","rifiuti non specificati altrimenti"],
["070300","rifiuti della produzione, formulazione, fornitura ed uso di coloranti e pigmenti organici (tranne 06 11)"],
["070301","*soluzioni acquose di lavaggio ed acque madri"],
["070303","*solventi organici alogenati, soluzioni di lavaggio ed acque madri"],
["070304","*altri solventi organici, soluzioni di lavaggio ed acque madri"],
["070307","*fondi e residui di reazione alogenati"],
["070308","*altri fondi e residui di reazione"],
["070309","*residui di filtrazione e assorbenti esauriti alogenati"],
["070310","*altri residui di filtrazione e assorbenti esauriti"],
["070311","*fanghi prodotti dal trattamento in loco degli effluenti, contenenti sostanze pericolose"],
["070312","fanghi prodotti dal trattamento in loco degli effluenti, diversi da quelli di cui alla voce 07 03 11"],
["070399","rifiuti non specificati altrimenti"],
["070400","rifiuti della produzione, formulazione, fornitura ed uso di prodotti fitosanitari (tranne 02 01 08 e 02 01 09),agenti conservativi del legno (tranne 03 02) ed altri biocidi organici"],
["070401","*soluzioni acquose di lavaggio ed acque madri"],
["070403","*solventi organici alogenati, soluzioni di lavaggio ed acque madri"],
["070404","*altri solventi organici, soluzioni di lavaggio ed acque madri"],
["070407","*fondi e residui di reazione alogenati"],
["070408","*altri fondi e residui di reazione"],
["070409","*residui di filtrazione e assorbenti esauriti alogenati"],
["070410","*altri residui di filtrazione e assorbenti esauriti"],
["070411","*fanghi prodotti dal trattamento in loco degli effluenti, contenenti sostanze pericolose"],
["070412","fanghi prodotti dal trattamento in loco degli effluenti, diversi da quelli di cui alla voce 07 04 11"],
["070413","*rifiuti solidi contenenti sostanze pericolose"],
["070499","rifiuti non specificati altrimenti"],
["070500","rifiuti della produzione, formulazione, fornitura ed uso di prodotti farmaceutici"],
["070501","*soluzioni acquose di lavaggio ed acque madri"],
["070503","*solventi organici alogenati, soluzioni di lavaggio ed acque madri"],
["070504","*altri solventi organici, soluzioni di lavaggio ed acque madri"],
["070507","*fondi e residui di reazione, alogenati"],
["070508","*altri fondi e residui di reazione"],
["070509","*residui di filtrazione e assorbenti esauriti, alogenati"],
["070510","*altri residui di filtrazione e assorbenti esauriti"],
["070511","*fanghi prodotti dal trattamento in loco degli effluenti, contenenti sostanze pericolose"],
["070512","fanghi prodotti dal trattamento in loco degli effluenti, diversi da quelli di cui alla voce 07 05 11"],
["070513","*rifiuti solidi contenenti sostanze pericolose"],
["070514","rifiuti solidi, diversi da quelli di cui alla voce 07 05 13"],
["070599","rifiuti non specificati altrimenti"],
["070600","rifiuti della produzione, formulazione, fornitura ed uso di grassi, lubrificanti, saponi, detergenti, disinfettanti e cosmetici"],
["070601","*soluzioni acquose di lavaggio ed acque madri"],
["070603","*solventi organici alogenati, soluzioni di lavaggio ed acque madri"],
["070604","*altri solventi organici, soluzioni di lavaggio ed acque madri"],
["070607","*fondi e residui di reazione, alogenati"],
["070608","*altri fondi e residui di reazione"],
["070609","*residui di filtrazione e assorbenti esauriti, alogenati"],
["070610","*altri residui di filtrazione e assorbenti esauriti"],
["070611","*fanghi prodotti dal trattamento in loco degli effluenti, contenenti sostanze pericolose"],
["070612","fanghi prodotti dal trattamento in loco degli effluenti, diversi da quelli di cui alla voce 07 06 11"],
["070699","rifiuti non specificati altrimenti"],
["070700","rifiuti della produzione, formulazione, fornitura ed uso di prodotti della chimica fine e di prodotti chimici non specificati altrimenti"],
["070701","*soluzioni acquose di lavaggio ed acque madri"],
["070703","*solventi organici alogenati, soluzioni di lavaggio ed acque madri"],
["070704","*altri solventi organici, soluzioni di lavaggio ed acque madri"],
["070707","*residui di distillazione e residui di reazione, alogenati"],
["070708","*altri residui di distillazione e residui di reazione"],
["070709","*residui di filtrazione e assorbenti esauriti, alogenati"],
["070710","*altri residui di filtrazione e assorbenti esauriti"],
["070711","*fanghi prodotti dal trattamento in loco degli effluenti, contenenti sostanze pericolose"],
["070712","fanghi prodotti dal trattamento in loco degli effluenti, diversi da quelli di cui alla voce 07 07 11"],
["070799","rifiuti non specificati altrimenti"],
["080000","RIFIUTI DELLA PRODUZIONE, FORMULAZIONE, FORNITURA ED USO DI RIVESTIMENTI (PITTURE, VERNICI E SMALTI VETRATI), ADESIVI, SIGILLANTI E INCHIOSTRI PER STAMPA"],
["080100","rifiuti della produzione, formulazione, fornitura ed uso e della rimozione di pitture e vernici"],
["080111","*pitture e vernici di scarto, contenenti solventi organici o altre sostanze pericolose"],
["080112","pitture e vernici di scarto, diverse da quelle di cui alla voce 08 01 11"],
["080113","*fanghi prodotti da pitture e vernici, contenenti solventi organici o altre sostanze pericolose"],
["080114","fanghi prodotti da pitture e vernici, diversi da quelli di cui alla voce 08 01 13"],
["080115","*fanghi acquosi contenenti pitture e vernici, contenenti solventi organici o altre sostanze pericolose"],
["080116","fanghi acquosi contenenti pitture e vernici, diversi da quelli di cui alla voce 08 01 15"],
["080117","*fanghi prodotti dalla rimozione di pitture e vernici, contenenti solventi organici o altre sostanze pericolose"],
["080118","fanghi prodotti dalla rimozione di pitture e vernici, diversi da quelli di cui alla voce 08 01 17"],
["080119","*sospensioni acquose contenenti pitture e vernici, contenenti solventi organici o altre sostanze pericolose"],
["080120","sospensioni acquose contenenti pitture e vernici, diverse da quelle di cui alla voce 08 01 19"],
["080121","*residui di vernici o di sverniciatori"],
["080199","rifiuti non specificati altrimenti"],
["080200","rifiuti della produzione, formulazione, fornitura ed uso di altri rivestimenti (inclusi materiali ceramici)"],
["080201","polveri di scarto di rivestimenti"],
["080202","fanghi acquosi contenenti materiali ceramici"],
["080203","sospensioni acquose contenenti materiali ceramici"],
["080299","rifiuti non specificati altrimenti"],
["080300","rifiuti della produzione, formulazione, fornitura ed uso di inchiostri per stampa"],
["080307","fanghi acquosi contenenti inchiostro"],
["080308","rifiuti liquidi acquosi contenenti inchiostro"],
["080312","*scarti di inchiostro, contenenti sostanze pericolose"],
["080313","scarti di inchiostro, diversi da quelli di cui alla voce 08 03 12"],
["080314","*fanghi di inchiostro, contenenti sostanze pericolose"],
["080315","fanghi di inchiostro, diversi da quelli di cui alla voce 08 03 14"],
["080316","*residui di soluzioni chimiche per incisione"],
["080317","*toner per stampa esauriti, contenenti sostanze pericolose"],
["080318","toner per stampa esauriti, diversi da quelli di cui alla voce 08 03 17"],
["080319","*oli dispersi"],
["080399","rifiuti non specificati altrimenti"],
["080400","rifiuti della produzione, formulazione, fornitura ed uso di adesivi e sigillanti (inclusi i prodotti impermeabilizzanti)"],
["080409","*adesivi e sigillanti di scarto, contenenti solventi organici o altre sostanze pericolose"],
["080410","adesivi e sigillanti di scarto, diversi da quelli di cui alla voce 08 04 09"],
["080411","*fanghi di adesivi e sigillanti, contenenti solventi organici o altre sostanze pericolose"],
["080412","fanghi di adesivi e sigillanti, diversi da quelli di cui alla voce 08 04 11"],
["080413","*fanghi acquosi contenenti adesivi e sigillanti, contenenti solventi organici o altre sostanze pericolose"],
["080414","fanghi acquosi contenenti adesivi e sigillanti, diversi da quelli di cui alla voce 08 04 13"],
["080415","*rifiuti liquidi acquosi contenenti adesivi e sigillanti, contenenti solventi organici o altre sostanze pericolose"],
["080416","rifiuti liquidi acquosi contenenti adesivi e sigillanti, diversi da quelli di cui alla voce 08 04 15"],
["080417","*olio di resina"],
["080499","rifiuti non specificati altrimenti"],
["080500","rifiuti non specificati altrimenti alla voce 08"],
["080501","*isocianati di scarto"],
["090000","RIFIUTI DELL'INDUSTRIA FOTOGRAFICA"],
["090100","rifiuti dell'industria fotografica"],
["090101","*soluzioni di sviluppo e attivanti a base acquosa"],
["090102","*soluzioni di sviluppo per lastre offset a base acquosa"],
["090103","*soluzioni di sviluppo a base di solventi"],
["090104","*soluzioni fissative"],
["090105","*soluzioni di lavaggio e soluzioni di arresto-fissaggio"],
["090106","*rifiuti contenenti argento prodotti dal trattamento in loco di rifiuti fotografici"],
["090107","carta e pellicole per fotografia, contenenti argento o composti dell'argento"],
["090108","carta e pellicole per fotografia, non contenenti argento o composti dell'argento"],
["090110","macchine fotografiche monouso senza batterie"],
["090111","*macchine fotografiche monouso contenenti batterie incluse nelle voci 16 06 01, 16 06 02 o 16 06 03"],
["090112","macchine fotografiche monouso diverse da quelle di cui alla voce 09 01 11"],
["090113","*rifiuti liquidi acquosi prodotti dal recupero in loco dell'argento, diversi da quelli di cui alla voce 09 01 06"],
["090199","rifiuti non specificati altrimenti"],
["100000","RIFIUTI PRODOTTI DA PROCESSI TERMICI"],
["100100","rifiuti prodotti da centrali termiche ed altri impianti termici (tranne 19)"],
["100101"," ceneri pesanti, scorie e polveri di caldaia (tranne le polveri di caldaia di cui alla voce 10 01 04)"],
["100102","ceneri leggere di carbone"],
["100103","ceneri leggere di torba e di legno non trattato"],
["100104","*ceneri leggere di olio combustibile e polveri di caldaia"],
["100105","rifiuti solidi prodotti da reazioni a base di calcio nei processi di desolforazione dei fumi"],
["100107","rifiuti fangosi prodotti da reazioni a base di calcio nei processi di desolforazione dei fumi"],
["100109","*acido solforico"],
["100113","*ceneri leggere prodotte da idrocarburi emulsionati usati come carburante"],
["100114","*ceneri pesanti, scorie e polveri di caldaia prodotte dal coincenerimento, contenenti sostanze pericolose"],
["100115"," ceneri pesanti, scorie e polveri di caldaia prodotte dal coincenerimento, diverse da quelli di cui alla voce 10 01 14"],
["100116","*ceneri leggere prodotte dal coincenerimento, contenenti sostanze pericolose"],
["100117","ceneri leggere prodotte dal coincenerimento, diverse da quelle di cui alla voce 10 01 16"],
["100118","*rifiuti prodotti dalla depurazione dei fumi, contenenti sostanze pericolose"],
["100119","rifiuti prodotti dalla depurazione dei fumi, diversi da quelli di cui alle voci 10 01 05, 10 01 07 e 10 01 18"],
["100120","*fanghi prodotti dal trattamento in loco degli effluenti, contenenti sostanze pericolose"],
["100121","fanghi prodotti dal trattamento in loco degli effluenti, diversi da quelli di cui alla voce 10 01 20"],
["100122","*fanghi acquosi da operazioni di pulizia caldaie, contenenti sostanze pericolose"],
["100123","fanghi acquosi da operazioni di pulizia caldaie, diversi da quelli di cui alla voce 10 01 22"],
["100124","sabbie dei reattori a letto fluidizzato"],
["100125","rifiuti dell'immagazzinamento e della preparazione del combustibile delle centrali termoelettriche a carbone"],
["100126","rifiuti prodotti dal trattamento delle acque di raffreddamento"],
["100199","rifiuti non specificati altrimenti"],
["100200","rifiuti dell'industria siderurgica"],
["100201","rifiuti del trattamento delle scorie"],
["100202","scorie non trattate"],
["100207","*rifiuti solidi prodotti dal trattamento dei fumi, contenenti sostanze pericolose"],
["100208","rifiuti prodotti dal trattamento dei fumi, diversi da quelli di cui alla voce 10 02 07"],
["100210","scaglie di laminazione"],
["100211","*rifiuti prodotti dal trattamento delle acque di raffreddamento, contenti oli"],
["100212","rifiuti prodotti dal trattamento delle acque di raffreddamento, diversi da quelli di cui alla voce 10 02 11"],
["100213","*fanghi e residui di filtrazione prodotti dal trattamento dei fumi, contenenti sostanze pericolose"],
["100214","fanghi e residui di filtrazione prodotti dal trattamento dei fumi, diversi da quelli di cui alla voce 10 02 13"],
["100215","altri fanghi e residui di filtrazione"],
["100299","rifiuti non specificati altrimenti"],
["100300","rifiuti della metallurgia termica dell'alluminio"],
["100302","frammenti di anodi"],
["100304","*scorie della produzione primaria"],
["100305","rifiuti di allumina"],
["100308","*scorie saline della produzione secondaria"],
["100309","*scorie nere della produzione secondaria"],
["100315","*schiumature infiammabili o che rilasciano, al contatto con l'acqua, gas infiammabili in quantità pericolose"],
["100316","schiumature diverse da quelle di cui alla voce 10 03 15"],
["100317","*rifiuti contenenti catrame della produzione degli anodi"],
["100318","rifiuti contenenti carbone della produzione degli anodi, diversi da quelli di cui alla voce 10 03 17"],
["100319","*polveri dei gas di combustione, contenenti sostanze pericolose"],
["100320","polveri dei gas di combustione, diverse da quelle di cui alla voce 10 03 19"],
["100321","*altre polveri e particolati (comprese quelle prodotte da mulini a palle), contenenti sostanze pericolose"],
["100322","altre polveri e particolati (comprese quelle prodotte da mulini a palle), diverse da quelle di cui alla voce 10 03 21"],
["100323","*rifiuti solidi prodotti dal trattamento dei fumi, contenenti sostanze pericolose"],
["100324","rifiuti prodotti dal trattamento dei fumi, diversi da quelli di cui alla voce 10 03 23"],
["100325","*fanghi e residui di filtrazione prodotti dal trattamento dei fumi, contenenti sostanze pericolose"],
["100326","fanghi e residui di filtrazione prodotti dal trattamento dei fumi, diversi da quelli di cui alla voce 10 03 25"],
["100327","*rifiuti prodotti dal trattamento delle acque di raffreddamento, contenenti oli"],
["100328","rifiuti prodotti dal trattamento delle acque di raffreddamento, diversi da quelli di cui alla voce 10 03 27"],
["100329","*rifiuti prodotti dal trattamento di scorie saline e scorie nere, contenenti sostanze pericolose"],
["100330","rifiuti prodotti dal trattamento di scorie saline e scorie nere, diversi da quelli di cui alla voce 10 03 29"],
["100399","rifiuti non specificati altrimenti"],
["100400","rifiuti della metallurgia termica del piombo"],
["100401","*scorie della produzione primaria e secondaria"],
["100402","*scorie e schiumature della produzione primaria e secondaria"],
["100403","*arsenato di calcio"],
["100404","*polveri dei gas di combustione"],
["100405","*altre polveri e particolato"],
["100406","*rifiuti solidi prodotti dal trattamento dei fumi"],
["100407","*fanghi e residui di filtrazione prodotti dal trattamento dei fumi"],
["100409","*rifiuti prodotti dal trattamento delle acque di raffreddamento, contenenti oli"],
["100410","rifiuti prodotti dal trattamento delle acque di raffreddamento, diversi da quelli di cui alla voce 10 04 09"],
["100499","rifiuti non specificati altrimenti"],
["100500","rifiuti della metallurgia termica dello zinco"],
["100501","scorie della produzione primaria e secondaria"],
["100503","*polveri dei gas di combustione"],
["100504","altre polveri e particolato"],
["100505","*rifiuti solidi prodotti dal trattamento dei fumi"],
["100506","*fanghi e residui di filtrazione prodotti dal trattamento dei fumi"],
["100508","*rifiuti prodotti dal trattamento delle acque di raffreddamento, contenenti oli"],
["100509","rifiuti prodotti dal trattamento delle acque di raffreddamento, diversi da quelli di cui alla voce 10 05 08"],
["100510","*scorie e schiumature infiammabili o che rilasciano, al contatto con l'acqua, gas infiammabili in quantità pericolose"],
["100511","scorie e schiumature diverse da quelle di cui alla voce 10 05 10"],
["100599","rifiuti non specificati altrimenti"],
["100600","rifiuti della metallurgia termica del rame"],
["100601","scorie della produzione primaria e secondaria"],
["100602","Scorie e schiumature della produzione primaria e secondaria"],
["100603","*polveri dei gas di combustione"],
["100604","altre polveri e particolato"],
["100606","*rifiuti solidi prodotti dal trattamento dei fumi"],
["100607","*fanghi e residui di filtrazione prodotti dal trattamento dei fumi"],
["100609","*rifiuti prodotti dal trattamento delle acque di raffreddamento, contenenti oli"],
["100610","rifiuti prodotti dal trattamento delle acque di raffreddamento, diversi da quelli di cui alla voce 10 06 09"],
["100699","rifiuti non specificati altrimenti"],
["100700","rifiuti della metallurgia termica di argento, oro e platino"],
["100701","scorie della produzione primaria e secondaria"],
["100702","scorie e schiumature della produzione primaria e secondaria"],
["100703","rifiuti solidi prodotti dal trattamento dei fumi"],
["100704","altre polveri e particolato"],
["100705","fanghi e residui di filtrazione prodotti dal trattamento dei fumi"],
["100707","*rifiuti prodotti dal trattamento delle acque di raffreddamento, contenenti oli"],
["100708","rifiuti prodotti dal trattamento delle acque di raffreddamento, diversi da quelli di cui alla voce 10 07 07"],
["100799","rifiuti non specificati altrimenti"],
["100800","rifiuti della metallurgia termica di altri minerali non ferrosi"],
["100804","polveri e particolato"],
["100808","*scorie salate della produzione primaria e secondaria"],
["100809","altre scorie"],
["100810","*scorie e schiumature infiammabili o che rilasciano, al contatto con l'acqua, gas infiammabili in quantità pericolose"],
["100811","impurità e schiumature diverse da quelle di cui alla voce 10 08 10"],
["100812","*rifiuti contenenti catrame derivante dalla produzione degli anodi"],
["100813","rifiuti contenenti carbonio derivanti dalla produzione di anodi, diversi da quelli di cui alla voce 10 08 12"],
["100814","frammenti di anodi"],
["100815","*polveri dei gas di combustione, contenenti sostanze pericolose"],
["100816","polveri dei gas di combustione, diverse da quelle di cui alla voce 10 08 15"],
["100817","*fanghi e residui di filtrazione prodotti dal trattamento dei fumi, contenenti sostanze pericolose"],
["100818","fanghi e residui di filtrazione prodotti dal trattamento dei fumi, diversi da quelli di cui alla voce 10 08 17"],
["100819","*rifiuti prodotti dal trattamento delle acque di raffreddamento, contenenti oli"],
["100820","rifiuti prodotti dal trattamento delle acque di raffreddamento, diversi da quelli di cui alla voce 10 08 19"],
["100899","rifiuti non specificati altrimenti"],
["100900","rifiuti della fusione di materiali ferrosi"],
["100903","scorie di fusione"],
["100905","*forme e anime da fonderia non utilizzate, contenenti sostanze pericolose"],
["100906","forme e anime da fonderia non utilizzate, diverse da quelle di cui alla voce 10 09 05"],
["100907","*forme e anime da fonderia utilizzate, contenenti sostanze pericolose"],
["100908","forme e anime da fonderia utilizzate, diverse da quelle di cui alla voce 10 09 07"],
["100909","*polveri dei gas di combustione contenenti sostanze pericolose"],
["100910","polveri dei gas di combustione diverse da quelle di cui alla voce 10 09 09"],
["100911","*altri particolati contenenti sostanze pericolose"],
["100912","altri particolati diversi da quelli di cui alla voce 10 09 11"],
["100913","*scarti di leganti contenenti sostanze pericolose"],
["100914","scarti di leganti diversi da quelli di cui alla voce 10 09 13"],
["100915","*scarti di prodotti rilevatori di crepe, contenenti sostanze pericolose"],
["100916","scarti di prodotti rilevatori di crepe, diversi da quelli di cui alla voce 10 09 15"],
["100999","rifiuti non specificati altrimenti"],
["101000","rifiuti della fusione di materiali non ferrosi"],
["101003","scorie di fusione"],
["101005","*forme e anime da fonderia non utilizzate, contenenti sostanze pericolose"],
["101006","forme e anime da fonderia non utilizzate, diverse da quelle di cui alla voce 10 10 05"],
["101007","*forme e anime da fonderia utilizzate, contenenti sostanze pericolose"],
["101008","forme e anime da fonderia utilizzate, diverse da quelle di cui alla voce 10 10 07"],
["101009","*polveri dei gas di combustione, contenenti sostanze pericolose"],
["101010","polveri dei gas di combustione, diverse da quelle di cui alla voce 10 10 09"],
["101011","*altri particolati contenenti sostanze pericolose"],
["101012","altri particolati diversi da quelli di cui alla voce 10 10 11"],
["101013","*scarti di leganti contenenti sostanze pericolose"],
["101014","scarti di leganti diversi da quelli di cui alla voce 10 10 13"],
["101015","*scarti di prodotti rilevatori di crepe, contenenti sostanze pericolose"],
["101016","scarti di prodotti rilevatori di crepe, diversi da quelli di cui alla voce 10 10 15"],
["101099","rifiuti non specificati altrimenti"],
["101100","rifiuti della fabbricazione del vetro e di prodotti di vetro"],
["101103","scarti di materiali in fibra a base di vetro"],
["101105","polveri e particolato"],
["101109","*residui di miscela di preparazione non sottoposti a trattamento termico, contenenti sostanze pericolose"],
["101110","residui di miscela di preparazione non sottoposti a trattamento termico, diverse da quelle di cui alla voce 10 11 09"],
["101111","*rifiuti di vetro in forma di particolato e polveri di vetro contenenti metalli pesanti (provenienti ad es. da tubi a raggi catodici)"],
["101112","rifiuti di vetro diversi da quelli di cui alla voce 10 11 11"],
["101113","*fanghi provenienti dalla lucidatura e dalla macinazione del vetro, contenenti sostanze pericolose"],
["101114","fanghi provenienti dalla lucidatura e dalla macinazione del vetro, diversi da quelli di cui alla voce 10 11 13"],
["101115","*rifiuti solidi prodotti dal trattamento dei fumi, contenenti sostanze pericolose"],
["101116","rifiuti prodotti dal trattamento dei fumi, diversi da quelli di cui alla voce 10 11 15"],
["101117","*fanghi e residui di filtrazione prodotti dal trattamento dei fumi, contenenti sostanze pericolose"],
["101118","fanghi e residui di filtrazione prodotti dal trattamento dei fumi, diversi da quelli di cui alla voce 10 11 17"],
["101119","*rifiuti solidi prodotti dal trattamento in loco degli effluenti, contenenti sostanze pericolose"],
["101120","rifiuti solidi prodotti dal trattamento in loco degli effluenti, diversi da quelli di cui alla voce 10 11 19"],
["101199","rifiuti non specificati altrimenti"],
["101200","rifiuti della fabbricazione di prodotti di ceramica, mattoni, mattonelle e materiali da costruzione"],
["101201","residui di miscela di preparazione non sottoposti a trattamento termico"],
["101203","polveri e particolato"],
["101205","fanghi e residui di filtrazione prodotti dal trattamento dei fumi"],
["101206","stampi di scarto"],
["101208","scarti di ceramica, mattoni, mattonelle e materiali da costruzione (sottoposti a trattamento termico)"],
["101209","*rifiuti solidi prodotti dal trattamento dei fumi, contenenti sostanze pericolose"],
["101210","rifiuti solidi prodotti dal trattamento dei fumi, diversi da quelli di cui alla voce 10 12 09"],
["101211","*rifiuti delle operazioni di smaltatura, contenenti metalli pesanti"],
["101212","rifiuti delle operazioni di smaltatura diversi da quelli di cui alla voce 10 12 11"],
["101213","fanghi prodotti dal trattamento in loco degli effluenti"],
["101299","rifiuti non specificati altrimenti"],
["101300","rifiuti della fabbricazione di cemento, calce e gesso e manufatti di tali materiali"],
["101301","residui di miscela di preparazione non sottoposti a trattamento termico"],
["101304","rifiuti di calcinazione e di idratazione della calce"],
["101306","polveri e particolato (eccetto quelli delle voci 10 13 12 e 10 13 13)"],
["101307","fanghi e residui di filtrazione prodotti dal trattamento dei fumi"],
["101309","*rifiuti della fabbricazione di amianto cemento, contenenti amianto"],
["101310","rifiuti della fabbricazione di amianto cemento, diversi da quelli di cui alla voce 10 13 09"],
["101311","rifiuti della produzione di materiali compositi a base di cemento, diversi da quelli di cui alle voci 10 13 09 e 10 13 10"],
["101312","*rifiuti solidi prodotti dal trattamento dei fumi, contenenti sostanze pericolose"],
["101313","rifiuti solidi prodotti dal trattamento dei fumi, diversi da quelli di cui alla voce 10 13 12"],
["101314","rifiuti e fanghi di cemento"],
["101399","rifiuti non specificati altrimenti"],
["101400","rifiuti prodotti dai forni crematori"],
["101401","*rifiuti prodotti dalla depurazione dei fumi, contenenti mercurio"],
["110000","RIFIUTI PRODOTTI DAL TRATTAMENTO CHIMICO SUPERFICIALE E DAL RIVESTIMENTO DI METALLI ED ALTRI MATERIALI; IDROMETALLURGIA NON FERROSA"],
["110100","rifiuti prodotti dal trattamento e ricopertura di metalli (ad esempio, processi galvanici, zincatura, decapaggio, pulitura elettrolitica, fosfatazione, sgrassaggio con alcali, anodizzazione)"],
["110105","*acidi di decappaggio"],
["110106","*acidi non specificati altrimenti"],
["110107","*basi di decappaggio"],
["110108","*fanghi di fosfatazione"],
["110109","*fanghi e residui di filtrazione, contenenti sostanze pericolose"],
["110110","fanghi e residui di filtrazione, diversi da quelli di cui alla voce 11 01 09"],
["110111","*soluzioni acquose di lavaggio, contenenti sostanze pericolose"],
["110112","soluzioni acquose di lavaggio, diverse da quelle di cui alla voce 11 01 11"],
["110113","*rifiuti di sgrassaggio contenenti sostanze pericolose"],
["110114","rifiuti di sgrassaggio diversi da quelli di cui alla voce 11 01 13"],
["110115","*eluati e fanghi di sistemi a membrana e sistemi a scambio ionico, contenenti sostanze pericolose"],
["110116","*resine a scambio ionico saturate o esaurite"],
["110198","*altri rifiuti contenenti sostanze pericolose"],
["110199","rifiuti non specificati altrimenti"],
["110200","rifiuti prodotti dalla lavorazione idrometallurgica di metalli non ferrosi"],
["110202","*rifiuti della lavorazione idrometallurgica dello zinco (compresi jarosite, goethite)"],
["110203","rifiuti della produzione di anodi per processi elettrolitici acquosi"],
["110205","*rifiuti della lavorazione idrometallurgica del rame, contenenti sostanze pericolose"],
["110206","rifiuti della lavorazione idrometallurgica del rame, diversi da quelli della voce 11 02 05"],
["110207","*altri rifiuti contenenti sostanze pericolose"],
["110299","rifiuti non specificati altrimenti"],
["110300","rifiuti solidi e fanghi prodotti da processi di rinvenimento"],
["110301","*rifiuti contenenti cianuro"],
["110302","*altri rifiuti"],
["110500","rifiuti prodotti da processi di galvanizzazione a caldo"],
["110501","zinco solido"],
["110502","ceneri di zinco"],
["110503","*rifiuti solidi prodotti dal trattamento dei fumi"],
["110504","*fondente esaurito"],
["110599","rifiuti non specificati altrimenti"],
["120000","RIFIUTI PRODOTTI DALLA LAVORAZIONE E DAL TRATTAMENTO FISICO E MECCANICO SUPERFICIALE DI METALLI E PLASTICA"],
["120100","rifiuti prodotti dalla lavorazione e dal trattamento fisico e meccanico superficiale di metalli e plastiche"],
["120101","limatura e trucioli di materiali ferrosi"],
["120102","polveri e particolato di materiali ferrosi"],
["120103","limatura, scaglie e polveri di metalli non ferrosi"],
["120104","polveri e particolato di materiali non ferrosi"],
["120105","limatura e trucioli di materiali plastici"],
["120106","*oli minerali per macchinari, contenenti alogeni (eccetto emulsioni e soluzioni)"],
["120107","*oli minerali per macchinari, non contenenti alogeni (eccetto emulsioni e soluzioni)"],
["120108","*emulsioni e soluzioni per macchinari, contenenti alogeni"],
["120109","*emulsioni e soluzioni per macchinari, non contenenti alogeni"],
["120110","*oli sintetici per macchinari"],
["120112","*cere e grassi esauriti"],
["120113","rifiuti di saldatura"],
["120114","*fanghi di lavorazione, contenenti sostanze pericolose"],
["120115","fanghi di lavorazione, diversi da quelli di cui alla voce 12 01 14"],
["120116","*residui di materiale di sabbiatura, contenente sostanze pericolose"],
["120117","residui di materiale di sabbiatura, diversi da quelli di cui alla voce 12 01 16"],
["120118","*fanghi metallici (fanghi di rettifica, affilatura e lappatura) contenenti olio"],
["120119","*oli per macchinari, facilmente biodegradabili"],
["120120","*corpi d'utensile e materiali di rettifica esauriti, contenenti sostanze pericolose"],
["120121","corpi d'utensile e materiali di rettifica esauriti, diversi da quelli di cui alla voce 12 01 20"],
["120199","rifiuti non specificati altrimenti"],
["120300","rifiuti prodotti da processi di sgrassatura ad acqua e vapore (tranne 11)"],
["120301","*soluzioni acquose di lavaggio"],
["120302","*rifiuti prodotti da processi di sgrassatura a vapore"],
["130000","OLI ESAURITI E RESIDUI DI COMBUSTIBILI LIQUIDI (tranne oli commestibili ed oli di cui ai capitoli 05, 12 e 19)"],
["130100","scarti di oli per circuiti idraulici"],
["130101","*oli per circuiti idraulici contenenti PCB (La definizione di PCB adottata nel presente elenco di rifiuti è quella contenuta nella direttiva 96/59/CE.)"],
["130104","*emulsioni clorurate"],
["130105","*emulsioni non clorurate"],
["130109","*oli minerali per circuiti idraulici, clorurati"],
["130110","*oli minerali per circuiti idraulici, non clorurati"],
["130111","*oli sintetici per circuiti idraulici"],
["130112","*oli per circuiti idraulici, facilmente biodegradabili"],
["130113","*altri oli per circuiti idraulici"],
["130200","scarti di olio motore, olio per ingranaggi e oli lubrificanti"],
["130204","*oli minerali per motori, ingranaggi e lubrificazione, clorurati"],
["130205","*oli minerali per motori, ingranaggi e lubrificazione, non clorurati"],
["130206","*oli sintetici per motori, ingranaggi e lubrificazione"],
["130207","*olio per motori, ingranaggi e lubrificazione, facilmente biodegradabile"],
["130208","*altri oli per motori, ingranaggi e lubrificazione"],
["130300","oli isolanti e oli termoconduttori usati"],
["130301","*oli isolanti e termoconduttori, contenenti PCB"],
["130306","*oli minerali isolanti e termoconduttori clorurati, diversi da quelli di cui alla voce 13 03 01"],
["130307","*oli minerali isolanti e termoconduttori non clorurati"],
["130308","*oli sintetici isolanti e termoconduttori"],
["130309","*oli isolanti e termoconduttori, facilmente biodegradabili"],
["130310","*altri oli isolanti e termoconduttori"],
["130400","oli di sentina"],
["130401","*oli di sentina della navigazione interna"],
["130402","*oli di sentina delle fognature dei moli"],
["130403","*altri oli di sentina della navigazione"],
["130500","prodotti di separazione olio/acqua"],
["130501","*rifiuti solidi delle camere a sabbia e di prodotti di separazione olio/acqua"],
["130502","*fanghi di prodotti di separazione olio/acqua"],
["130503","*fanghi da collettori"],
["130506","*oli prodotti dalla separazione olio/acqua"],
["130507","*acque oleose prodotte dalla separazione olio/acqua"],
["130508","*miscugli di rifiuti delle camere a sabbia e dei prodotti di separazione olio/acqua"],
["130700","residui di combustibili liquidi"],
["130701","*olio combustibile e carburante diesel"],
["130702","*benzina"],
["130703","*altri carburanti (comprese le miscele)"],
["130800","rifiuti di oli non specificati altrimenti"],
["130801","*fanghi ed emulsioni prodotti dai processi di dissalazione"],
["130802","*altre emulsioni"],
["130899","*rifiuti non specificati altrimenti"],
["140000","SOLVENTI ORGANICI, REFRIGERANTI E PROPELLENTI DI SCARTO (tranne 07 e 08)"],
["140600","rifiuti di solventi organici, refrigeranti e propellenti di schiuma/aerosol"],
["140601","*clorofluorocarburi, HCFC, HFC1"],
["140602","*altri solventi e miscele di solventi, alogenati"],
["140603","*altri solventi e miscele di solventi"],
["140604","*fanghi o rifiuti solidi, contenenti solventi alogenati"],
["140605","*fanghi o rifiuti solidi, contenenti altri solventi"],
["150000","RIFIUTI DI IMBALLAGGIO, ASSORBENTI, STRACCI, MATERIALI FILTRANTI E INDUMENTI PROTETTIVI (NON SPECIFICATI ALTRIMENTI)"],
["150100","imballaggi (compresi i rifiuti urbani di imballaggio oggetto di raccolta differenziata)"],
["150101","imballaggi in carta e cartone"],
["150102","imballaggi in plastica"],
["150103","imballaggi in legno"],
["150104","imballaggi metallici"],
["150105","imballaggi compositi"],
["150106","imballaggi in materiali misti"],
["150107","imballaggi in vetro"],
["150109","imballaggi in materia tessile"],
["150110","*imballaggi contenenti residui di sostanze pericolose o contaminati da tali sostanze"],
["150111","*imballaggi metallici contenenti matrici solide porose pericolose (ad esempio amianto), compresi i contenitori a pressione vuoti"],
["150200","assorbenti, materiali filtranti, stracci e indumenti protettivi"],
["150202","*assorbenti, materiali filtranti (inclusi filtri dell'olio non specificati altrimenti), stracci e indumenti protettivi, contaminati da sostanze pericolose"],
["150203","assorbenti, materiali filtranti, stracci e indumenti protettivi, diversi da quelli di cui alla voce 15 02 02"],
["160000","RIFIUTI NON SPECIFICATI ALTRIMENTI NELL'ELENCO"],
["160100","veicoli fuori uso appartenenti a diversi modi di trasporto (comprese le macchine mobili non stradali) e rifiuti prodotti dallo smantellamento di veicoli fuori uso e dalla manutenzione di veicoli (tranne 13, 14, 16 06 e 16 08)"],
["160103","pneumatici fuori uso"],
["160104","*veicoli fuori uso"],
["160106","veicoli fuori uso, non contenenti liquidi né altre componenti pericolose"],
["160107","*filtri dell'olio"],
["160108","*componenti contenenti mercurio"],
["160109","*componenti contenenti PCB"],
["160110","*componenti esplosivi (ad esempio 'air bag')"],
["160111","*pastiglie per freni, contenenti amianto"],
["160112","pastiglie per freni, diverse da quelle di cui alla voce 16 01 11"],
["160113","*liquidi per freni"],
["160114","*liquidi antigelo contenenti sostanze pericolose"],
["160115","liquidi antigelo diversi da quelli di cui alla voce 16 01 14"],
["160116","serbatoi per gas liquido"],
["160117","metalli ferrosi"],
["160118","metalli non ferrosi"],
["160119","plastica"],
["160120","vetro"],
["160121","*componenti pericolosi diversi da quelli di cui alle voci da 16 01 07 a 16 01 11, 16 01 13 e 16 01 14"],
["160122","componenti non specificati altrimenti"],
["160199","rifiuti non specificati altrimenti"],
["160200","rifiuti provenienti da apparecchiature elettriche ed elettroniche"],
["160209","*trasformatori e condensatori contenenti PCB"],
["160210","*apparecchiature fuori uso contenenti PCB o da essi contaminate, diverse da quelle di cui alla voce 16 02 09"],
["160211","*apparecchiature fuori uso, contenenti clorofluorocarburi, HCFC, HFC"],
["160212","*apparecchiature fuori uso, contenenti amianto in fibre libere"],
["160213","*apparecchiature fuori uso, contenenti componenti pericolosi (2) diversi da quelli di cui alle voci 16 02 09 e 16 02 12"],
["160214","apparecchiature fuori uso, diverse da quelle di cui alle voci da 16 02 09 a 16 02 13"],
["160215","*componenti pericolosi rimossi da apparecchiature fuori uso"],
["160216","componenti rimossi da apparecchiature fuori uso, diversi da quelli di cui alla voce 16 02 15"],
["160300","prodotti fuori specifica e prodotti inutilizzati"],
["160303","*rifiuti inorganici, contenenti sostanze pericolose"],
["160304","rifiuti inorganici, diversi da quelli di cui alla voce 16 03 03"],
["160305","*rifiuti organici, contenenti sostanze pericolose"],
["160306","rifiuti organici, diversi da quelli di cui alla voce 16 03 05"],
["160307","*mercurio metallico (nuovo codice CER)"],
["160400","esplosivi di scarto"],
["160401","*munizioni di scarto"],
["160402","*fuochi artificiali di scarto"],
["160403","*altri esplosivi di scarto"],
["160500","gas in contenitori a pressione e prodotti chimici di scarto"],
["160504","*gas in contenitori a pressione (compresi gli halon), contenenti sostanze pericolose"],
["160505","gas in contenitori a pressione, diversi da quelli di cui alla voce 16 05 04"],
["160506","*sostanze chimiche di laboratorio contenenti o costituite da sostanze pericolose, comprese le miscele di sostanze chimiche di laboratorio"],
["160507","*sostanze chimiche inorganiche di scarto contenenti o costituite da sostanze pericolose"],
["160508","*sostanze chimiche organiche di scarto contenenti o costituite da sostanze pericolose"],
["160509","sostanze chimiche di scarto diverse da quelle di cui alle voci 16 05 06, 16 05 07 e 16 05 08"],
["160600","batterie ed accumulatori"],
["160601","*batterie al piombo"],
["160602","*batterie al nichel-cadmio"],
["160603","*batterie contenenti mercurio"],
["160604","batterie alcaline (tranne 16 06 03)"],
["160605","altre batterie ed accumulatori"],
["160606","*elettroliti di batterie ed accumulatori, oggetto di raccolta differenziata"],
["160700","rifiuti della pulizia di serbatoi per trasporto e stoccaggio e di fusti (tranne 05 e 13)"],
["160708","*rifiuti contenenti olio"],
["160709","*rifiuti contenenti altre sostanze pericolose"],
["160799","rifiuti non specificati altrimenti"],
["160800","catalizzatori esauriti"],
["160801","catalizzatori esauriti contenenti oro, argento, renio, rodio, palladio, iridio o platino (tranne 16 08 07)"],
["160802","*catalizzatori esauriti contenenti metalli di transizione (3) pericolosi o composti di metalli di transizione pericolosi"],
["160803","catalizzatori esauriti contenenti metalli di transizione o composti di metalli di transizione, non specificati altrimenti"],
["160804","catalizzatori esauriti da cracking catalitico fluido (tranne 16 08 07)"],
["160805","*catalizzatori esauriti contenenti acido fosforico"],
["160806","*liquidi esauriti usati come catalizzatori"],
["160807","*catalizzatori esauriti contaminati da sostanze pericolose"],
["160900","sostanze ossidanti"],
["160901","*permanganati, ad esempio permanganato di potassio"],
["160902","*cromati, ad esempio cromato di potassio, dicromato di potassio o di sodio"],
["160903","*perossidi, ad esempio perossido d'idrogeno"],
["160904","*sostanze ossidanti non specificate altrimenti"],
["161000","rifiuti liquidi acquosi destinati ad essere trattati fuori sito"],
["161001","*rifiuti liquidi acquosi, contenenti sostanze pericolose"],
["161002","rifiuti liquidi acquosi, diversi da quelle di cui alla voce 16 10 01"],
["161003","*concentrati acquosi, contenenti sostanze pericolose"],
["161004","concentrati acquosi, diversi da quelli di cui alla voce 16 10 03"],
["161100","scarti di rivestimenti e materiali refrattari"],
["161101","*rivestimenti e materiali refrattari a base di carbone provenienti da processi metallurgici, contenenti sostanze pericolose"],
["161102","rivestimenti e materiali refrattari a base di carbone provenienti dalle lavorazioni metallurgiche, diversi da quelli di cui alla voce 16 11 01"],
["161103","*altri rivestimenti e materiali refrattari provenienti da processi metallurgici, contenenti sostanze pericolose"],
["161104","altri rivestimenti e materiali refrattari provenienti da processi metallurgici, diversi da quelli di cui alla voce 16 11 03"],
["161105","*rivestimenti e materiali refrattari provenienti da lavorazioni non metallurgiche, contenenti sostanze pericolose"],
["161106","rivestimenti e materiali refrattari provenienti da lavorazioni non metallurgiche, diversi da quelli di cui alla voce 16 11 05"],
["170000","RIFIUTI DELLE OPERAZIONI DI COSTRUZIONE E DEMOLIZIONE (COMPRESO IL TERRENO PROVENIENTE DA SITI CONTAMINATI)"],
["170100","cemento, mattoni, mattonelle e ceramiche"],
["170101","cemento"],
["170102","mattoni"],
["170103","mattonelle e ceramiche"],
["170106","*miscugli o frazioni separate di cemento, mattoni, mattonelle e ceramiche, contenenti sostanze pericolose"],
["170107","miscugli o frazioni separate di cemento, mattoni, mattonelle e ceramiche, diverse da quelle di cui alla voce 17 01 06"],
["170200","legno, vetro e plastica"],
["170201","legno"],
["170202","vetro"],
["170203","plastica"],
["170204","*vetro, plastica e legno contenenti sostanze pericolose o da esse contaminati"],
["170300","miscele bituminose, catrame di carbone e prodotti contenenti catrame"],
["170301","*miscele bituminose contenenti catrame di carbone"],
["170302","miscele bituminose diverse da quelle di cui alla voce 17 03 01"],
["170303","*catrame di carbone e prodotti contenenti catrame"],
["170400","metalli (incluse le loro leghe)"],
["170401","rame, bronzo, ottone"],
["170402","alluminio"],
["170403","piombo"],
["170404","zinco"],
["170405","ferro e acciaio"],
["170406","stagno"],
["170407","metalli misti"],
["170409","*rifiuti metallici contaminati da sostanze pericolose"],
["170410","*cavi, impregnati di olio, di catrame di carbone o di altre sostanze pericolose"],
["170411","cavi, diversi da quelli di cui alla voce 17 04 10"],
["170500","terra (compresa quella proveniente da siti contaminati), rocce e materiale di dragaggio"],
["170503","*terra e rocce, contenenti sostanze pericolose"],
["170504","terra e rocce, diverse da quelle di cui alla voce 17 05 03"],
["170505","*fanghi di dragaggio, contenente sostanze pericolose"],
["170506","fanghi di dragaggio, diversa da quella di cui alla voce 17 05 05"],
["170507","*pietrisco per massicciate ferroviarie, contenente sostanze pericolose"],
["170508","pietrisco per massicciate ferroviarie, diverso da quello di cui alla voce 17 05 07"],
["170600","materiali isolanti e materiali da costruzione contenenti amianto"],
["170601","*materiali isolanti contenenti amianto"],
["170603","*altri materiali isolanti contenenti o costituiti da sostanze pericolose"],
["170604","materiali isolanti diversi da quelli di cui alle voci 17 06 01 e 17 06 03"],
["170605","*materiali da costruzione contenenti amianto"],
["170800","materiali da costruzione a base di gesso"],
["170801","*materiali da costruzione a base di gesso contaminati da sostanze pericolose"],
["170802","materiali da costruzione a base di gesso diversi da quelli di cui alla voce 17 08 01"],
["170900","altri rifiuti dell'attività di costruzione e demolizione"],
["170901","*rifiuti dell'attività di costruzione e demolizione, contenenti mercurio"],
["170902","*rifiuti dell'attività di costruzione e demolizione, contenenti PCB (ad esempio sigillanti contenenti PCB, pavimentazioni a base di resina contenenti PCB, elementi stagni in vetro contenenti PCB, condensatori contenenti PCB)"],
["170903","*altri rifiuti dell'attività di costruzione e demolizione (compresi rifiuti misti) contenenti sostanze pericolose"],
["170904","rifiuti misti dell'attività di costruzione e demolizione, diversi da quelli di cui alle voci 17 09 01, 17 09 02 e 17 09 03"],
["180000","RIFIUTI PRODOTTI DAL SETTORE SANITARIO E VETERINARIO O DA ATTIVITÀ DI RICERCA COLLEGATE(tranne i rifiuti di cucina e di ristorazione non direttamente provenienti da trattamento terapeutico)"],
["180100","rifiuti dei reparti di maternità e rifiuti legati a diagnosi, trattamento e prevenzione delle malattie negli esseri umani"],
["180101","oggetti da taglio (eccetto 18 01 03)"],
["180102","parti anatomiche ed organi incluse le sacche per il plasma e le riserve di sangue (tranne 18 01 03)"],
["180103","*rifiuti che devono essere raccolti e smaltiti applicando precauzioni particolari per evitare infezioni"],
["180104","rifiuti che non devono essere raccolti e smaltiti applicando precauzioni particolari per evitare infezioni (es. bende, ingessature, lenzuola, indumenti monouso, assorbenti igienici)"],
["180106","*sostanze chimiche pericolose o contenenti sostanze pericolose"],
["180107","sostanze chimiche diverse da quelle di cui alla voce 18 01 06"],
["180108","*medicinali citotossici e citostatici"],
["180109","medicinali diversi da quelli di cui alla voce 18 01 08"],
["180110","*rifiuti di amalgama prodotti da interventi odontoiatrici"],
["180200","rifiuti legati alle attività di ricerca e diagnosi, trattamento e prevenzione delle malattie negli animali"],
["180201","oggetti da taglio (eccetto 18 02 02)"],
["180202","*rifiuti che devono essere raccolti e smaltiti applicando precauzioni particolari per evitare infezioni"],
["180203","rifiuti che non devono essere raccolti e smaltiti applicando precauzioni particolari per evitare infezioni"],
["180205","*sostanze chimiche pericolose o contenenti sostanze pericolose"],
["180206","sostanze chimiche diverse da quelle di cui alla voce 18 02 05"],
["180207","*medicinali citotossici e citostatici"],
["180208","medicinali diversi da quelli di cui alla voce 18 02 07"],
["190000","RIFIUTI PRODOTTI DA IMPIANTI DI TRATTAMENTO DEI RIFIUTI, IMPIANTI DI TRATTAMENTO DELLE ACQUE REFLUE FUORI SITO, NONCHÉ DALLA POTABILIZZAZIONE DELL'ACQUA E DALLA SUA PREPARAZIONE PER USO INDUSTRIALE"],
["190100","rifiuti da incenerimento o pirolisi di rifiuti"],
["190102","materiali ferrosi estratti da ceneri pesanti"],
["190105","*residui di filtrazione prodotti dal trattamento dei fumi"],
["190106","*rifiuti liquidi acquosi prodotti dal trattamento dei fumi e di altri rifiuti liquidi acquosi"],
["190107","*rifiuti solidi prodotti dal trattamento dei fumi"],
["190110","*carbone attivo esaurito, impiegato per il trattamento dei fumi"],
["190111","*ceneri pesanti e scorie, contenenti sostanze pericolose"],
["190112","ceneri pesanti e scorie, diverse da quelle di cui alla voce 19 01 11"],
["190113","*ceneri leggere, contenenti sostanze pericolose"],
["190114","ceneri leggere, diverse da quelle di cui alla voce 19 01 13"],
["190115","*polveri di caldaia, contenenti sostanze pericolose"],
["190116","polveri di caldaia, diverse da quelle di cui alla voce 19 01 15"],
["190117","*rifiuti della pirolisi, contenenti sostanze pericolose"],
["190118","rifiuti della pirolisi, diversi da quelli di cui alla voce 19 01 17"],
["190119","sabbie dei reattori a letto fluidizzato"],
["190199","rifiuti non specificati altrimenti"],
["190200","rifiuti prodotti da specifici trattamenti chimico-fisici di rifiuti industriali (comprese decromatazione, decianizzazione, neutralizzazione)"],
["190203","rifiuti premiscelati composti esclusivamente da rifiuti non pericolosi"],
["190204","*rifiuti premiscelati contenenti almeno un rifiuto pericoloso"],
["190205","*fanghi prodotti da trattamenti chimico-fisici, contenenti sostanze pericolose"],
["190206","fanghi prodotti da trattamenti chimico-fisici, diversi da quelli di cui alla voce 19 02 05"],
["190207","*oli e concentrati prodotti da processi di separazione"],
["190208","*rifiuti combustibili liquidi, contenenti sostanze pericolose"],
["190209","*rifiuti combustibili solidi, contenenti sostanze pericolose"],
["190210","rifiuti combustibili, diversi da quelli di cui alle voci 19 02 08 e 19 02 09"],
["190211","*altri rifiuti contenenti sostanze pericolose"],
["190299","rifiuti non specificati altrimenti"],
["190300","rifiuti stabilizzati/solidificati (4)"],
["190304","*rifiuti contrassegnati come pericolosi, parzialmente (5) stabilizzati"],
["190305","rifiuti stabilizzati diversi da quelli di cui alla voce 19 03 04"],
["190306","*rifiuti contrassegnati come pericolosi, solidificati"],
["190307","rifiuti solidificati diversi da quelli di cui alla voce 19 03 06"],
["190308","*mercurio parzialmente stabilizzato (nuovo codice CER)"],
["190400","rifiuti vetrificati e rifiuti di vetrificazione"],
["190401","rifiuti vetrificati"],
["190402","*ceneri leggere ed altri rifiuti dal trattamento dei fumi"],
["190403","*fase solida non vetrificata"],
["190404","rifiuti liquidi acquosi prodotti dalla tempra di rifiuti vetrificati"],
["190500","rifiuti prodotti dal trattamento aerobico di rifiuti solidi"],
["190501","parte di rifiuti urbani e simili non compostata"],
["190502","parte di rifiuti animali e vegetali non compostata"],
["190503","compost fuori specifica"],
["190599","rifiuti non specificati altrimenti"],
["190600","rifiuti prodotti dal trattamento anaerobico dei rifiuti"],
["190603","liquidi prodotti dal trattamento anaerobico di rifiuti urbani"],
["190604","digestato prodotto dal trattamento anaerobico di rifiuti urbani"],
["190605","liquidi prodotti dal trattamento anaerobico di rifiuti di origine animale o vegetale"],
["190606","digestato prodotto dal trattamento anaerobico di rifiuti di origine animale o vegetale"],
["190699","rifiuti non specificati altrimenti"],
["190700","percolato di discarica"],
["190702","*percolato di discarica, contenente sostanze pericolose"],
["190703","percolato di discarica, diverso da quello di cui alla voce 19 07 02"],
["190800","rifiuti prodotti dagli impianti per il trattamento delle acque reflue, non specificati altrimenti"],
["190801","residui di vagliatura"],
["190802","rifiuti dell'eliminazione della sabbia"],
["190805","fanghi prodotti dal trattamento delle acque reflue urbane"],
["190806","*resine a scambio ionico saturate o esaurite"],
["190807","*soluzioni e fanghi di rigenerazione delle resine a scambio ionico"],
["190808","*rifiuti prodotti da sistemi a membrana, contenenti sostanze pericolose"],
["190809","miscele di oli e grassi prodotte dalla separazione olio/acqua, contenenti esclusivamente oli e grassi commestibili"],
["190810","*miscele di oli e grassi prodotte dalla separazione olio/acqua, diverse da quelle di cui alla voce 19 08 09"],
["190811","*fanghi prodotti dal trattamento biologico delle acque reflue industriali, contenenti sostanze pericolose"],
["190812","fanghi prodotti dal trattamento biologico delle acque reflue industriali, diversi da quelli di cui alla voce 19 08 11"],
["190813","*fanghi contenenti sostanze pericolose prodotti da altri trattamenti delle acque reflue industriali"],
["190814","fanghi prodotti da altri trattamenti delle acque reflue industriali, diversi da quelli di cui alla voce 19 08 13"],
["190899","rifiuti non specificati altrimenti"],
["190900","rifiuti prodotti dalla potabilizzazione dell'acqua o dalla sua preparazione per uso industriale"],
["190901","rifiuti solidi prodotti dai processi di filtrazione e vaglio primari"],
["190902","fanghi prodotti dai processi di chiarificazione dell'acqua"],
["190903","fanghi prodotti dai processi di decarbonatazione"],
["190904","carbone attivo esaurito"],
["190905","resine a scambio ionico saturate o esaurite"],
["190906","soluzioni e fanghi di rigenerazione delle resine a scambio ionico"],
["190999","rifiuti non specificati altrimenti"],
["191000","rifiuti prodotti da operazioni di frantumazione di rifiuti contenenti metallo"],
["191001","rifiuti di ferro e acciaio"],
["191002","rifiuti di metalli non ferrosi"],
["191003","*fluff - frazione leggera e polveri, contenenti sostanze pericolose"],
["191004","fluff - frazione leggera e polveri, diversi da quelli di cui alla voce 19 10 03"],
["191005","*altre frazioni, contenenti sostanze pericolose"],
["191006","altre frazioni, diverse da quelle di cui alla voce 19 10 05"],
["191100","rifiuti prodotti dalla rigenerazione dell'olio"],
["191101","*filtri di argilla esauriti"],
["191102","*catrami acidi"],
["191103","*rifiuti liquidi acquosi"],
["191104","*rifiuti prodotti dalla purificazione di carburanti tramite basi"],
["191105","*fanghi prodotti dal trattamento in loco degli effluenti, contenenti sostanze pericolose"],
["191106","fanghi prodotti dal trattamento in loco degli effluenti, diversi da quelli di cui alla voce 19 11 05"],
["191107","*rifiuti prodotti dalla purificazione dei fumi"],
["191199","rifiuti non specificati altrimenti"],
["191200","rifiuti prodotti dal trattamento meccanico dei rifiuti (ad esempio selezione, triturazione, compattazione, riduzione in pellet) non specificati altrimenti"],
["191201","carta e cartone"],
["191202","metalli ferrosi"],
["191203","metalli non ferrosi"],
["191204","plastica e gomma"],
["191205","vetro"],
["191206","*legno contenente sostanze pericolose"],
["191207","legno diverso da quello di cui alla voce 19 12 06"],
["191208","prodotti tessili"],
["191209","minerali (ad esempio sabbia, rocce)"],
["191210","rifiuti combustibili (combustibile da rifiuti)"],
["191211","*altri rifiuti (compresi materiali misti) prodotti dal trattamento meccanico dei rifiuti, contenenti sostanze pericolose"],
["191212","altri rifiuti (compresi materiali misti) prodotti dal trattamento meccanico dei rifiuti, diversi da quelli di cui alla voce 19 12 11"],
["191300","rifiuti prodotti dalle operazioni di bonifica di terreni e risanamento delle acque di falda"],
["191301","*rifiuti solidi prodotti dalle operazioni di bonifica dei terreni, contenenti sostanze pericolose"],
["191302","rifiuti solidi prodotti dalle operazioni di bonifica dei terreni, diversi da quelli di cui alla voce 19 13 01"],
["191303","*fanghi prodotti dalle operazioni di bonifica dei terreni, contenenti sostanze pericolose"],
["191304","fanghi prodotti dalle operazioni di bonifica dei terreni, diversi da quelli di cui alla voce 19 13 03"],
["191305","*fanghi prodotti dalle operazioni di risanamento delle acque di falda, contenenti sostanze pericolose"],
["191306","fanghi prodotti dalle operazioni di risanamento delle acque di falda, diversi da quelli di cui alla voce 19 13 05"],
["191307","*rifiuti liquidi acquosi e concentrati acquosi prodotti dalle operazioni di risanamento delle acque di falda, contenenti sostanze pericolose"],
["191308","rifiuti liquidi acquosi e concentrati acquosi prodotti dalle operazioni di risanamento delle acque di falda, diversi da quelli di cui alla voce 19 13 07"],
["200000","RIFIUTI URBANI (RIFIUTI DOMESTICI E ASSIMILABILI PRODOTTI DA ATTIVITÀ COMMERCIALI E INDUSTRIALI NONCHÉ DALLE ISTITUZIONI) INCLUSI I RIFIUTI DELLA RACCOLTA DIFFERENZIATA"],
["200100","frazioni oggetto di raccolta differenziata (tranne 15 01)"],
["200101","carta e cartone"],
["200102","vetro"],
["200108","rifiuti biodegradabili di cucine e mense"],
["200110","abbigliamento"],
["200111","prodotti tessili"],
["200113","*solventi"],
["200114","*acidi"],
["200115","*sostanze alcaline"],
["200117","*prodotti fotochimici"],
["200119","*pesticidi"],
["200121","*tubi fluorescenti ed altri rifiuti contenenti mercurio"],
["200123","*apparecchiature fuori uso contenenti clorofluorocarburi"],
["200125","oli e grassi commestibili"],
["200126","*oli e grassi diversi da quelli di cui alla voce 20 01 25"],
["200127","*vernici, inchiostri, adesivi e resine contenenti sostanze pericolose"],
["200128","vernici, inchiostri, adesivi e resine diversi da quelli di cui alla voce 20 01 27"],
["200129","*detergenti contenenti sostanze pericolose"],
["200130","detergenti diversi da quelli di cui alla voce 20 01 29"],
["200131","*medicinali citotossici e citostatici"],
["200132","medicinali diversi da quelli di cui alla voce 20 01 31"],
["200133","*batterie e accumulatori di cui alle voci 16 06 01, 16 06 02 e 16 06 03 nonché batterie e accumulatori non suddivisi contenenti tali batterie"],
["200134","batterie e accumulatori diversi da quelli di cui alla voce 20 01 33"],
["200135","*apparecchiature elettriche ed elettroniche fuori uso, diverse da quelle di cui alla voce 20 01 21 e 20 01 23, contenenti componenti pericolosi (6)"],
["200136","apparecchiature elettriche ed elettroniche fuori uso, diverse da quelle di cui alle voci 20 01 21, 20 01 23 e 20 01 35"],
["200137","*legno, contenente sostanze pericolose"],
["200138","legno, diverso da quello di cui alla voce 20 01 37"],
["200139","plastica"],
["200140","metallo"],
["200141","rifiuti prodotti dalla pulizia di camini e ciminiere"],
["200199","altre frazioni non specificate altrimenti"],
["200200","rifiuti prodotti da giardini e parchi (inclusi i rifiuti provenienti da cimiteri)"],
["200201","rifiuti biodegradabili"],
["200202","terra e roccia"],
["200203","altri rifiuti non biodegradabili"],
["200300","altri rifiuti urbani"],
["200301","rifiuti urbani non differenziati"],
["200302","rifiuti dei mercati"],
["200303","residui della pulizia stradale"],
["200304","fanghi delle fosse settiche"],
["200306","rifiuti della pulizia delle fognature"],
["200307","rifiuti ingombranti"],
["200399","rifiuti urbani non specificati altrimenti"]

		);
		$keys = ['cdcer','dscer'];
		// Loop through each user above and create the record for them in the database
		foreach ($values as $value) {
			CodiceCer::create(array_combine($keys,array_pad($value,count($keys),null)));
		}

		Model::reguard();   
    }
}
