(function (ctx_1, data_1, root) {
function isArray(arr){return Array.isArray(arr);}
function isFunction(func){return (typeof func === 'function');}
function c(val, ctx) {if (typeof val !== "undefined" && val !== null) {if (isFunction(val)) {return val.call(ctx);} else return val;} else return "";}
root = root || ctx_1 || {};
var r = '';
r +='\n	<div class="page">\n		<div class="navbar">\n			<div class="navbar-bg"></div>\n			<div class="navbar-inner sliding">\n				<div class="left">\n					<a href="#" class="back link">\n						<i class="icon icon-back"></i>\n						<span class="if-not-md">';r += (Template7Helpers._e).call(ctx_1, 'Back', {hash:{}, data: data_1 || {}, fn: function empty() { return ''; }, inverse: function empty() { return ''; }, root: root, parents: [ctx_1]});r +='</span>\n					</a>\n				</div>\n				<div class="title">';r += (Template7Helpers._e).call(ctx_1, 'Comuni', {hash:{}, data: data_1 || {}, fn: function empty() { return ''; }, inverse: function empty() { return ''; }, root: root, parents: [ctx_1]});r +='</div>\n				<div class="right">\n					<!-- Link to enable searchbar -->\n					<a class="link icon-only searchbar-enable" data-searchbar=".searchbar-2form">\n						<i class="icon f7-icons if-not-md">search</i>\n						<i class="icon material-icons md-only">search</i>\n					</a>\n				</div>\n				<form data-search-container=".search-list" data-search-in=".item-title" class="searchbar searchbar-expandable searchbar-init searchbar-2form">\n					<div class="searchbar-inner">\n						<div class="searchbar-input-wrap">\n							<input type="search" placeholder="Search">\n							<i class="searchbar-icon"></i>\n							<span class="input-clear-button"></span>\n						</div>\n						<span class="searchbar-disable-button if-not-aurora">';r += (Template7Helpers._e).call(ctx_1, 'Cancel', {hash:{}, data: data_1 || {}, fn: function empty() { return ''; }, inverse: function empty() { return ''; }, root: root, parents: [ctx_1]});r +='</span>\n					</div>\n				</form>\n			</div>\n		</div>\n		\n		<div class="page-content">		\n			<div class="block-title">';r += (Template7Helpers._e).call(ctx_1, 'Comuni e numero impianti:', {hash:{}, data: data_1 || {}, fn: function empty() { return ''; }, inverse: function empty() { return ''; }, root: root, parents: [ctx_1]});r +='</div>\n			<div class="list search-list searchbar-found">\n				<ul>\n					';r += (Template7Helpers.each).call(ctx_1, ctx_1.rs, {hash:{}, data: data_1 || {}, fn: (function (ctx_2, data_2) {
var r = '';
r +='\n					<li>\n						<a href="/impianti/comuni/';r += c(ctx_2.comune, ctx_2);r +='/tipi/" class="item-link item-content">\n							<div class="item-inner">\n								<div class="item-title">';r += c(ctx_2.comune, ctx_2);r +='</div>\n								<div class="item-after"> <span class="badge">';r += c(ctx_2.cnt, ctx_2);r +='</span></div>\n							</div>\n						</a>\n					</li>\n					';
return r;}), inverse: function empty() { return ''; }, root: root, parents: [ctx_1]});r +='\n					\n				</ul>\n			</div>\n		</div>\n	</div>\n';
return r;})