<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Crypt;
use Illuminate\Support\Facades\Hash;
use App\Models\Codici_cer;


class LookupSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
		Model::unguard();

		//DB::table('lookup')->delete();
		
	    $keys = ['tag','tx1','tx2','tx3','tx4'];
		$values = array(
['acronimo','hom','home page','links per home'],
['acronimo','tat','tipo attivita'],
	['tat','manutenzione ordinaria'],
	['tat','manutenzione straordinaria'],
	
['acronimo','moi','tipi di manutenzione ordinarie Imhoff'],
	['moi','pulizia'],
	['moi','sfalcio'],
	['moi','asporti'],
	
['acronimo','msi','tipi di manutenzione straordinarie Imhoff'],
	['msi','cancello'],
	['msi','recinzione'],
	['msi','chiusini'],
	
['acronimo','cim','categorie impianto'],
	['cim','DP','Depuratore'],
	['cim','IM','Imhoff'],
	['cim','SF','Sfioratore'],
	['cim','SL','Sollevatore'],
	['cim','DI','Disabbiatore'],
	['cim','DE','Decantazione'],

['acronimo','tim ','tipi impianto'],
	['tim','DP','Depuratore'],
	['tim','DI','Disabbiatore'],
	['tim','DE','I-Decantazione'],
	['tim','IM','Imhoff'],
	['tim','SF','Sfioratore'],
	['tim','SF','Sfioratore_D'],
	['tim','SF','Sfioratore_I'],
	['tim','SF','Sfioratore_S'],
	['tim','SO','Sollevamento'],
	
	

['acronimo','aas','aziende asporti'	],

['acronimo','cfa','nomi depuratori abili per conferimento'],
	['cfa','Paludi'],
	['cfa','Lana'],
['acronimo','rol','ruoli'		],
	['rol','Tecnico Responsabile'		],
	['rol','Operaio'		],
	['rol','Operaio Specializzato'		],
['acronimo','sqd','Squadre Impianti'		],
	['sqd','A1'],
	['sqd','A2'],
	['sqd','A3'],				
	['sqd','B1'],
	['sqd','B2'],
	['sqd','B3'],
	['sqd','C1'],
	['sqd','C2'],
	['sqd','C3'],
//-------------------------------------------------
['acronimo','cer','codice cer', "I rifiuti contrassegnati nell'elenco in rosso con un asterisco '*' sono rifiuti pericolosi ai sensi della direttiva 2008/98/CE relativa ai rifiuti pericolosi"],
//-------------------------------------------------
["cer","010000","RIFIUTI DERIVANTI DA PROSPEZIONE, ESTRAZIONE DA MINIERA O CAVA, NONCHÉ DAL TRATTAMENTO FISICO O CHIMICO DI MINERALI"],
["cer","010100","Rifiuti prodotti dall'estrazione di minerali"],
["cer","010101","rifiuti da estrazione di minerali metalliferi"],
["cer","010102","rifiuti da estrazione di minerali non metalliferi"],
["cer","010300","rifiuti prodotti da trattamenti chimici e fisici di minerali metalliferi"],
["cer","010304","*sterili che possono generare acido prodotti dalla lavorazione di minerale solforoso"],
["cer","010305","*altri sterili contenenti sostanze pericolose"],
["cer","010306","sterili diversi da quelli di cui alle voci 01 03 04 e 01 03 05"],
["cer","010307","*altri rifiuti contenenti sostanze pericolose prodotti da trattamenti chimici e fisici di minerali metalliferi"],
["cer","010308","polveri e residui affini diversi da quelli di cui alla voce 01 03 07"],
["cer","010309","fanghi rossi derivanti dalla produzione di allumina, diversi da quelli di cui alla voce 01 03 10"],
["cer","010310","*fanghi rossi derivanti dalla produzione di allumina contenenti sostanze pericolose, diversi da quelli di cui alla voce 01 03 07. (nuovo codice CER)"],
["cer","010399","rifiuti non specificati altrimenti"],
["cer","010400","rifiuti prodotti da trattamenti chimici e fisici di minerali non metalliferi"],
["cer","010407","*rifiuti contenenti sostanze pericolose, prodotti da trattamenti chimici e fisici di minerali non metalliferi"],
["cer","010408","scarti di ghiaia e pietrisco, diversi da quelli di cui alla voce 01 04 07"],
["cer","010409","scarti di sabbia e argilla"],
["cer","010410","polveri e residui affini, diversi da quelli di cui alla voce 01 04 07"],
["cer","010411","rifiuti della lavorazione di potassa e salgemma, diversi da quelli di cui alla voce 01 04 07"],
["cer","010412","sterili ed altri residui del lavaggio e della pulitura di minerali, diversi da quelli di cui alle voci 01 04 07 e 01 04 11"],
["cer","010413","rifiuti prodotti dal taglio e dalla segagione della pietra, diversi da quelli di cui alla voce 01 04 07"],
["cer","010499","rifiuti non specificati altrimenti"],
["cer","010500","fanghi di perforazione ed altri rifiuti di perforazione"],
["cer","010504","fanghi e rifiuti di perforazione di pozzi per acque dolci"],
["cer","010505","*fanghi e rifiuti di perforazione contenenti oli"],
["cer","010506","*fanghi di perforazione ed altri rifiuti di perforazione contenenti sostanze pericolose"],
["cer","010507","fanghi e rifiuti di perforazione contenenti barite, diversi da quelli delle voci 01 05 05 e 01 05 06"],
["cer","010508","fanghi e rifiuti di perforazione contenenti cloruri, diversi da quelli delle voci 01 05 05 e 01 05 06"],
["cer","010599","rifiuti non specificati altrimenti"],
["cer","020000","RIFIUTI PRODOTTI DA AGRICOLTURA, ORTICOLTURA, ACQUACOLTURA, SELVICOLTURA, CACCIA E PESCA, TRATTAMENTO E PREPARAZIONE DI ALIMENTI"],
["cer","020100","rifiuti prodotti da agricoltura, orticoltura, acquacoltura, selvicoltura, caccia e pesca"],
["cer","020101","fanghi da operazioni di lavaggio e pulizia"],
["cer","020102","scarti di tessuti animali"],
["cer","020103","scarti di tessuti vegetali"],
["cer","020104","rifiuti plastici (ad esclusione degli imballaggi)"],
["cer","020105","rifiuti agrochimici"],
["cer","020106","feci animali, urine e letame (comprese le lettiere usate), effluenti, raccolti separatamente e trattati fuori sito"],
["cer","020107","rifiuti della silvicoltura"],
["cer","020108","*rifiuti agrochimici contenenti sostanze pericolose"],
["cer","020109","rifiuti agrochimici diversi da quelli della voce 02 01 08"],
["cer","020199","rifiuti non specificati altrimenti"],
["cer","020200","rifiuti della preparazione e del trattamento di carne, pesce ed altri alimenti di origine animale"],
["cer","020201","fanghi da operazioni di lavaggio e pulizia"],
["cer","020202","scarti di tessuti animali"],
["cer","020203","scarti inutilizzabili per il consumo o la trasformazion"],
["cer","020204","fanghi prodotti dal trattamento in loco degli effluenti"],
["cer","020299","rifiuti non specificati altrimenti"],
["cer","020300","rifiuti della preparazione e del trattamento di frutta, verdura, cereali, oli alimentari, cacao, caffè, tè e tabacco; della produzione di conserve alimentari; della produzione di lievito ed estratto di lievito; della preparazione e fermentazione di melassa"],
["cer","020301","fanghi prodotti da operazioni di lavaggio, pulizia, sbucciatura, centrifugazione e separazione di componenti"],
["cer","020302","rifiuti legati all'impiego di conservanti"],
["cer","020303","rifiuti prodotti dall'estrazione tramite solvente"],
["cer","020304","scarti inutilizzabili per il consumo o la trasformazione"],
["cer","020305","fanghi prodotti dal trattamento in loco degli effluenti"],
["cer","020399","rifiuti non specificati altrimenti"],
["cer","020400","rifiuti prodotti dalla raffinazione dello zucchero"],
["cer","020401","terriccio residuo delle operazioni di pulizia e lavaggio delle barbabietole"],
["cer","020402","carbonato di calcio fuori specifica"],
["cer","020403","fanghi prodotti dal trattamento in loco degli effluenti"],
["cer","020499","rifiuti non specificati altrimenti"],
["cer","020500","rifiuti dell'industria lattiero-casearia"],
["cer","020501","scarti inutilizzabili per il consumo o la trasformazione"],
["cer","020502","fanghi prodotti dal trattamento in loco degli effluenti"],
["cer","020599","rifiuti non specificati altrimenti"],
["cer","020600","rifiuti dell'industria dolciaria e della panificazione"],
["cer","020601","scarti inutilizzabili per il consumo o la trasformazione"],
["cer","020602","rifiuti legati all'impiego di conservanti"],
["cer","020603","fanghi prodotti dal trattamento in loco degli effluenti"],
["cer","020699","rifiuti non specificati altrimenti"],
["cer","020700","rifiuti della produzione di bevande alcoliche ed analcoliche (tranne caffè, tè e cacao)"],
["cer","020701","rifiuti prodotti dalle operazioni di lavaggio, pulizia e macinazione della materia prima"],
["cer","020702","rifiuti prodotti dalla distillazione di bevande alcoliche"],
["cer","020703","rifiuti prodotti dai trattamenti chimici"],
["cer","020704","scarti inutilizzabili per il consumo o la trasformazione"],
["cer","020705","fanghi prodotti dal trattamento in loco degli effluenti"],
["cer","020799","rifiuti non specificati altrimenti"],
["cer","030000","RIFIUTI DELLA LAVORAZIONE DEL LEGNO E DELLA PRODUZIONE DI PANNELLI, MOBILI, POLPA, CARTA E CARTONE"],
["cer","030100","rifiuti della lavorazione del legno e della produzione di pannelli e mobili"],
["cer","030101","scarti di corteccia e sughero"],
["cer","030104","*segatura, trucioli, residui di taglio, legno, pannelli di truciolare e piallacci contenenti sostanze pericolose"],
["cer","030105","segatura, trucioli, residui di taglio, legno, pannelli di truciolare e piallacci diversi da quelli di cui alla voce 03 01 04"],
["cer","030199","rifiuti non specificati altrimenti"],
["cer","030200 ","rifiuti dei trattamenti conservativi del legno"],
["cer","030201","*prodotti per i trattamenti conservativi del legno contenenti composti organici non alogenati"],
["cer","030202","*prodotti per i trattamenti conservativi del legno contenenti composti organici clorurati"],
["cer","030203","*prodotti per i trattamenti conservativi del legno contenenti composti organometallici"],
["cer","030204","*prodotti per i trattamenti conservativi del legno contenenti composti inorganici"],
["cer","030205","*altri prodotti per i trattamenti conservativi del legno contenenti sostanze pericolose"],
["cer","030299","prodotti per i trattamenti conservativi del legno non specificati altrimenti"],
["cer","030300","rifiuti della produzione e della lavorazione di polpa, carta e cartone"],
["cer","030301","scarti di corteccia e legno"],
["cer","030302","fanghi di recupero dei bagni di macerazione (green liquor)"],
["cer","030305","fanghi prodotti dai processi di disinchiostrazione nel riciclaggio della carta"],
["cer","030307","scarti della separazione meccanica nella produzione di polpa da rifiuti di carta e cartone"],
["cer","030308","scarti della selezione di carta e cartone destinati ad essere riciclati"],
["cer","030309","fanghi di scarto contenenti carbonato di calcio"],
["cer","030310","scarti di fibre e fanghi contenenti fibre, riempitivi e prodotti di rivestimento generati dai processi di separazione meccanica"],
["cer","030311","fanghi prodotti dal trattamento in loco degli effluenti, diversi da quelli di cui alla voce 03 03 10"],
["cer","030399","rifiuti non specificati altrimenti"],
["cer","040000","RIFIUTI DELLA LAVORAZIONE DI PELLI E PELLICCE, NONCHÉ DELL'INDUSTRIA TESSILE"],
["cer","040100","rifiuti della lavorazione di pelli e pellicce"],
["cer","040101","carniccio e frammenti di calce"],
["cer","040102","rifiuti di calcinazione"],
["cer","040103","*bagni di sgrassatura esauriti contenenti solventi senza fase liquida"],
["cer","040104","liquido di concia contenente cromo"],
["cer","040105","liquido di concia non contenente cromo"],
["cer","040106","fanghi, prodotti in particolare dal trattamento in loco degli effluenti, contenenti cromo"],
["cer","040107","fanghi, prodotti in particolare dal trattamento in loco degli effluenti, non contenenti cromo"],
["cer","040108","cuoio conciato (scarti, cascami, ritagli, polveri di lucidatura) contenenti cromo"],
["cer","040109","rifiuti delle operazioni di confezionamento e finitura"],
["cer","040199","rifiuti non specificati altrimenti"],
["cer","010200 ","rifiuti dell'industria tessile"],
["cer","040209","rifiuti da materiali compositi (fibre impregnate, elastomeri, plastomeri)"],
["cer","040210","materiale organico proveniente da prodotti naturali (ad es. grasso, cera)"],
["cer","040214","*rifiuti provenienti da operazioni di finitura, contenenti solventi organici"],
["cer","040215","rifiuti da operazioni di finitura, diversi da quelli di cui alla voce 04 02 14"],
["cer","040216","*tinture e pigmenti, contenenti sostanze pericolose"],
["cer","040217","tinture e pigmenti, diversi da quelli di cui alla voce 04 02 16"],
["cer","040219","*fanghi prodotti dal trattamento in loco degli effluenti, contenenti sostanze pericolose"],
["cer","040220","fanghi prodotti dal trattamento in loco degli effluenti, diversi da quelli di cui alla voce 04 02 19"],
["cer","040221","rifiuti da fibre tessili grezze"],
["cer","040222","rifiuti da fibre tessili lavorate"],
["cer","040299","rifiuti non specificati altrimenti"],
["cer","050000","RIFIUTI DELLA RAFFINAZIONE DEL PETROLIO, PURIFICAZIONE DEL GAS NATURALE E TRATTAMENTO PIROLITICO DEL CARBONE"],
["cer","050100","rifiuti della raffinazione del petrolio"],
["cer","050102","*fanghi da processi di dissalazione"],
["cer","050103","*morchie depositate sul fondo dei serbatoi"],
["cer","050104","*fanghi acidi prodotti da processi di alchilazione"],
["cer","050105","*perdite di olio"],
["cer","050106","*fanghi oleosi prodotti dalla manutenzione di impianti e apparecchiature"],
["cer","050107","*catrami acidi"],
["cer","050108","*altri catrami"],
["cer","050109","*fanghi prodotti dal trattamento in loco degli effluenti, contenenti sostanze pericolose"],
["cer","050110","fanghi prodotti dal trattamento in loco degli effluenti, diversi da quelli di cui alla voce 05 01 09"],
["cer","050111","*rifiuti prodotti dalla purificazione di carburanti tramite basi"],
["cer","050112","*acidi contenenti oli"],
["cer","050113","fanghi residui dell'acqua di alimentazione delle caldaie"],
["cer","050114","rifiuti prodotti dalle torri di raffreddamento"],
["cer","050115","*filtri di argilla esauriti"],
["cer","050116","rifiuti contenenti zolfo prodotti dalla desolforizzazione del petrolio"],
["cer","050117","bitumi"],
["cer","050199","rifiuti non specificati altrimenti"],
["cer","050600","rifiuti prodotti dal trattamento pirolitico del carbone"],
["cer","050601","*catrami acidi"],
["cer","050603","*altri catrami"],
["cer","050604","rifiuti prodotti dalle torri di raffreddamento"],
["cer","050699","rifiuti non specificati altrimenti"],
["cer","050700","rifiuti prodotti dalla purificazione e dal trasporto di gas naturale"],
["cer","050701","*rifiuti contenenti mercurio"],
["cer","050702","rifiuti contenenti zolfo"],
["cer","050799","rifiuti non specificati altrimenti"],
["cer","060000","RIFIUTI DEI PROCESSI CHIMICI INORGANICI"],
["cer","060100","rifiuti della produzione, formulazione, fornitura ed uso di acidi"],
["cer","060101","*acido solforico ed acido solforoso"],
["cer","060102","*acido cloridrico"],
["cer","060103","*acido fluoridrico"],
["cer","060104","*acido fosforico e fosforoso"],
["cer","060105","*acido nitrico e acido nitroso"],
["cer","060106","*altri acidi"],
["cer","060199","rifiuti non specificati altrimenti"],
["cer","060200","rifiuti della produzione, formulazione, fornitura ed uso di basi"],
["cer","060201","*idrossido di calcio"],
["cer","060203","*idrossido di ammonio"],
["cer","060204","*idrossido di sodio e di potassio"],
["cer","060205","*altre basi"],
["cer","060299","rifiuti non specificati altrimenti"],
["cer","060300","rifiuti della produzione, formulazione, fornitura ed uso di sali, loro soluzioni e ossidi metallici"],
["cer","060311","*sali e loro soluzioni, contenenti cianuri"],
["cer","060313","*sali e loro soluzioni, contenenti metalli pesanti"],
["cer","060314","sali e loro soluzioni, diversi da quelli di cui alle voci 06 03 11 e 06 03 13"],
["cer","060315","*ossidi metallici contenenti metalli pesanti"],
["cer","060316","ossidi metallici, diversi da quelli di cui alla voce 06 03 15"],
["cer","060399","rifiuti non specificati altrimenti"],
["cer","060400","rifiuti contenenti metalli, diversi da quelli di cui alla voce 06 03"],
["cer","060403","*rifiuti contenenti arsenico"],
["cer","060404","*rifiuti contenenti mercurio"],
["cer","060405","*rifiuti contenenti altri metalli pesanti"],
["cer","060499","rifiuti non specificati altrimenti"],
["cer","060500","fanghi prodotti dal trattamento in loco degli effluenti"],
["cer","060502","*fanghi prodotti dal trattamento in loco degli effluenti, contenenti sostanze pericolose"],
["cer","060503","fanghi prodotti dal trattamento in loco degli effluenti, diversi da quelli di cui alla voce 06 05 02"],
["cer","060600","rifiuti della produzione, formulazione, fornitura ed uso di prodotti chimici contenenti zolfo, dei processi chimici dello zolfo e dei processi di desolforazione"],
["cer","060602","*rifiuti contenenti solfuri pericolosi"],
["cer","060603","rifiuti contenenti solfuri, diversi da quelli di cui alla voce 06 06 02"],
["cer","060699","rifiuti non specificati altrimenti"],
["cer","060700","rifiuti della produzione, formulazione, fornitura ed uso di prodotti alogeni e dei processi chimici degli alogeni"],
["cer","060701","*rifiuti dei processi elettrolitici, contenenti amianto"],
["cer","060702","*carbone attivato dalla produzione di cloro"],
["cer","060703","*fanghi di solfati di bario, contenenti mercurio"],
["cer","060704","*soluzioni ed acidi, ad es. acido di contatto"],
["cer","060799","rifiuti non specificati altrimenti"],
["cer","060800","rifiuti della produzione, formulazione, fornitura ed uso del silicio e dei suoi derivati"],
["cer","060802","*rifiuti contenenti clorosilano"],
["cer","060899","rifiuti non specificati altrimenti"],
["cer","060900","rifiuti della produzione, formulazione, fornitura ed uso di prodotti fosforosi e dei processi chimici del fosforo"],
["cer","060902","scorie fosforose"],
["cer","060903","*rifiuti prodotti da reazioni a base di calcio contenenti o contaminati da sostanze pericolose"],
["cer","060904","rifiuti prodotti da reazioni a base di calcio, diversi da quelli di cui alla voce 06 09 03"],
["cer","060999","rifiuti non specificati altrimenti"],
["cer","061000","rifiuti della produzione, formulazione, fornitura ed uso di prodotti chimici contenenti azoto, dei processi chimici dell'azoto e della produzione di fertilizzanti"],
["cer","061002","*rifiuti contenenti sostanze pericolose"],
["cer","061099","rifiuti non specificati altrimenti"],
["cer","061100","rifiuti dalla produzione di pigmenti inorganici ed opacificanti"],
["cer","061101","rifiuti prodotti da reazioni a base di calcio nella produzione di diossido di titanio"],
["cer","061199","rifiuti non specificati altrimenti"],
["cer","061300","rifiuti di processi chimici inorganici non specificati altrimenti"],
["cer","061301","*prodotti fitosanitari, agenti conservativi del legno ed altri biocidi inorganici"],
["cer","061302","*carbone attivato esaurito (tranne 06 07 02)"],
["cer","061303","nerofumo"],
["cer","061304","*rifiuti della lavorazione dell'amianto"],
["cer","061305","*fuliggine"],
["cer","061399","rifiuti non specificati altrimenti"],
["cer","070000","RIFIUTI DEI PROCESSI CHIMICI ORGANICI"],
["cer","070100","rifiuti della produzione, formulazione, fornitura ed uso di prodotti chimici organici di base"],
["cer","070101","*soluzioni acquose di lavaggio ed acque madri"],
["cer","070103","*solventi organici alogenati, soluzioni di lavaggio ed acque madri"],
["cer","070104","*altri solventi organici, soluzioni di lavaggio ed acque madri"],
["cer","070107","*fondi e residui di reazione, alogenati"],
["cer","070108","*altri fondi e residui di reazione"],
["cer","070109","*residui di filtrazione e assorbenti esauriti, alogenati"],
["cer","070110","*altri residui di filtrazione e assorbenti esauriti"],
["cer","070111","*fanghi prodotti dal trattamento in loco degli effluenti, contenenti sostanze pericolose"],
["cer","070112","fanghi prodotti dal trattamento in loco degli effluenti, diversi da quelli di cui alla voce 07 01 11"],
["cer","070199","rifiuti non specificati altrimenti"],
["cer","070200","rifiuti della produzione, formulazione, fornitura ed uso (PFFU) di plastiche, gomme sintetiche e fibre artificiali"],
["cer","070201","*soluzioni acquose di lavaggio ed acque madri"],
["cer","070203","*solventi organici alogenati, soluzioni di lavaggio ed acque madri"],
["cer","070204","*altri solventi organici, soluzioni di lavaggio ed acque madri"],
["cer","070207","*fondi e residui di reazione, alogenati"],
["cer","070208","*altri fondi e residui di reazione"],
["cer","070209","*residui di filtrazione e assorbenti esauriti, alogenati"],
["cer","070210","*altri residui di filtrazione e assorbenti esauriti"],
["cer","070211","*fanghi prodotti dal trattamento in loco degli effluenti, contenenti sostanze pericolose"],
["cer","070212","fanghi prodotti dal trattamento in loco degli effluenti, diversi da quelli di cui alla voce 07 02 11"],
["cer","070213","rifiuti plastici"],
["cer","070214","*rifiuti prodotti da additivi, contenenti sostanze pericolose"],
["cer","070215","rifiuti prodotti da additivi, diversi da quelli di cui alla voce 07 02 14"],
["cer","070216","*rifiuti contenenti silicone pericoloso"],
["cer","070217","rifiuti contenenti siliconi diversi da quelli di cui alla voce 07 02 16"],
["cer","070299","rifiuti non specificati altrimenti"],
["cer","070300","rifiuti della produzione, formulazione, fornitura ed uso di coloranti e pigmenti organici (tranne 06 11)"],
["cer","070301","*soluzioni acquose di lavaggio ed acque madri"],
["cer","070303","*solventi organici alogenati, soluzioni di lavaggio ed acque madri"],
["cer","070304","*altri solventi organici, soluzioni di lavaggio ed acque madri"],
["cer","070307","*fondi e residui di reazione alogenati"],
["cer","070308","*altri fondi e residui di reazione"],
["cer","070309","*residui di filtrazione e assorbenti esauriti alogenati"],
["cer","070310","*altri residui di filtrazione e assorbenti esauriti"],
["cer","070311","*fanghi prodotti dal trattamento in loco degli effluenti, contenenti sostanze pericolose"],
["cer","070312","fanghi prodotti dal trattamento in loco degli effluenti, diversi da quelli di cui alla voce 07 03 11"],
["cer","070399","rifiuti non specificati altrimenti"],
["cer","070400","rifiuti della produzione, formulazione, fornitura ed uso di prodotti fitosanitari (tranne 02 01 08 e 02 01 09),agenti conservativi del legno (tranne 03 02) ed altri biocidi organici"],
["cer","070401","*soluzioni acquose di lavaggio ed acque madri"],
["cer","070403","*solventi organici alogenati, soluzioni di lavaggio ed acque madri"],
["cer","070404","*altri solventi organici, soluzioni di lavaggio ed acque madri"],
["cer","070407","*fondi e residui di reazione alogenati"],
["cer","070408","*altri fondi e residui di reazione"],
["cer","070409","*residui di filtrazione e assorbenti esauriti alogenati"],
["cer","070410","*altri residui di filtrazione e assorbenti esauriti"],
["cer","070411","*fanghi prodotti dal trattamento in loco degli effluenti, contenenti sostanze pericolose"],
["cer","070412","fanghi prodotti dal trattamento in loco degli effluenti, diversi da quelli di cui alla voce 07 04 11"],
["cer","070413","*rifiuti solidi contenenti sostanze pericolose"],
["cer","070499","rifiuti non specificati altrimenti"],
["cer","070500","rifiuti della produzione, formulazione, fornitura ed uso di prodotti farmaceutici"],
["cer","070501","*soluzioni acquose di lavaggio ed acque madri"],
["cer","070503","*solventi organici alogenati, soluzioni di lavaggio ed acque madri"],
["cer","070504","*altri solventi organici, soluzioni di lavaggio ed acque madri"],
["cer","070507","*fondi e residui di reazione, alogenati"],
["cer","070508","*altri fondi e residui di reazione"],
["cer","070509","*residui di filtrazione e assorbenti esauriti, alogenati"],
["cer","070510","*altri residui di filtrazione e assorbenti esauriti"],
["cer","070511","*fanghi prodotti dal trattamento in loco degli effluenti, contenenti sostanze pericolose"],
["cer","070512","fanghi prodotti dal trattamento in loco degli effluenti, diversi da quelli di cui alla voce 07 05 11"],
["cer","070513","*rifiuti solidi contenenti sostanze pericolose"],
["cer","070514","rifiuti solidi, diversi da quelli di cui alla voce 07 05 13"],
["cer","070599","rifiuti non specificati altrimenti"],
["cer","070600","rifiuti della produzione, formulazione, fornitura ed uso di grassi, lubrificanti, saponi, detergenti, disinfettanti e cosmetici"],
["cer","070601","*soluzioni acquose di lavaggio ed acque madri"],
["cer","070603","*solventi organici alogenati, soluzioni di lavaggio ed acque madri"],
["cer","070604","*altri solventi organici, soluzioni di lavaggio ed acque madri"],
["cer","070607","*fondi e residui di reazione, alogenati"],
["cer","070608","*altri fondi e residui di reazione"],
["cer","070609","*residui di filtrazione e assorbenti esauriti, alogenati"],
["cer","070610","*altri residui di filtrazione e assorbenti esauriti"],
["cer","070611","*fanghi prodotti dal trattamento in loco degli effluenti, contenenti sostanze pericolose"],
["cer","070612","fanghi prodotti dal trattamento in loco degli effluenti, diversi da quelli di cui alla voce 07 06 11"],
["cer","070699","rifiuti non specificati altrimenti"],
["cer","070700","rifiuti della produzione, formulazione, fornitura ed uso di prodotti della chimica fine e di prodotti chimici non specificati altrimenti"],
["cer","070701","*soluzioni acquose di lavaggio ed acque madri"],
["cer","070703","*solventi organici alogenati, soluzioni di lavaggio ed acque madri"],
["cer","070704","*altri solventi organici, soluzioni di lavaggio ed acque madri"],
["cer","070707","*residui di distillazione e residui di reazione, alogenati"],
["cer","070708","*altri residui di distillazione e residui di reazione"],
["cer","070709","*residui di filtrazione e assorbenti esauriti, alogenati"],
["cer","070710","*altri residui di filtrazione e assorbenti esauriti"],
["cer","070711","*fanghi prodotti dal trattamento in loco degli effluenti, contenenti sostanze pericolose"],
["cer","070712","fanghi prodotti dal trattamento in loco degli effluenti, diversi da quelli di cui alla voce 07 07 11"],
["cer","070799","rifiuti non specificati altrimenti"],
["cer","080000","RIFIUTI DELLA PRODUZIONE, FORMULAZIONE, FORNITURA ED USO DI RIVESTIMENTI (PITTURE, VERNICI E SMALTI VETRATI), ADESIVI, SIGILLANTI E INCHIOSTRI PER STAMPA"],
["cer","080100","rifiuti della produzione, formulazione, fornitura ed uso e della rimozione di pitture e vernici"],
["cer","080111","*pitture e vernici di scarto, contenenti solventi organici o altre sostanze pericolose"],
["cer","080112","pitture e vernici di scarto, diverse da quelle di cui alla voce 08 01 11"],
["cer","080113","*fanghi prodotti da pitture e vernici, contenenti solventi organici o altre sostanze pericolose"],
["cer","080114","fanghi prodotti da pitture e vernici, diversi da quelli di cui alla voce 08 01 13"],
["cer","080115","*fanghi acquosi contenenti pitture e vernici, contenenti solventi organici o altre sostanze pericolose"],
["cer","080116","fanghi acquosi contenenti pitture e vernici, diversi da quelli di cui alla voce 08 01 15"],
["cer","080117","*fanghi prodotti dalla rimozione di pitture e vernici, contenenti solventi organici o altre sostanze pericolose"],
["cer","080118","fanghi prodotti dalla rimozione di pitture e vernici, diversi da quelli di cui alla voce 08 01 17"],
["cer","080119","*sospensioni acquose contenenti pitture e vernici, contenenti solventi organici o altre sostanze pericolose"],
["cer","080120","sospensioni acquose contenenti pitture e vernici, diverse da quelle di cui alla voce 08 01 19"],
["cer","080121","*residui di vernici o di sverniciatori"],
["cer","080199","rifiuti non specificati altrimenti"],
["cer","080200","rifiuti della produzione, formulazione, fornitura ed uso di altri rivestimenti (inclusi materiali ceramici)"],
["cer","080201","polveri di scarto di rivestimenti"],
["cer","080202","fanghi acquosi contenenti materiali ceramici"],
["cer","080203","sospensioni acquose contenenti materiali ceramici"],
["cer","080299","rifiuti non specificati altrimenti"],
["cer","080300","rifiuti della produzione, formulazione, fornitura ed uso di inchiostri per stampa"],
["cer","080307","fanghi acquosi contenenti inchiostro"],
["cer","080308","rifiuti liquidi acquosi contenenti inchiostro"],
["cer","080312","*scarti di inchiostro, contenenti sostanze pericolose"],
["cer","080313","scarti di inchiostro, diversi da quelli di cui alla voce 08 03 12"],
["cer","080314","*fanghi di inchiostro, contenenti sostanze pericolose"],
["cer","080315","fanghi di inchiostro, diversi da quelli di cui alla voce 08 03 14"],
["cer","080316","*residui di soluzioni chimiche per incisione"],
["cer","080317","*toner per stampa esauriti, contenenti sostanze pericolose"],
["cer","080318","toner per stampa esauriti, diversi da quelli di cui alla voce 08 03 17"],
["cer","080319","*oli dispersi"],
["cer","080399","rifiuti non specificati altrimenti"],
["cer","080400","rifiuti della produzione, formulazione, fornitura ed uso di adesivi e sigillanti (inclusi i prodotti impermeabilizzanti)"],
["cer","080409","*adesivi e sigillanti di scarto, contenenti solventi organici o altre sostanze pericolose"],
["cer","080410","adesivi e sigillanti di scarto, diversi da quelli di cui alla voce 08 04 09"],
["cer","080411","*fanghi di adesivi e sigillanti, contenenti solventi organici o altre sostanze pericolose"],
["cer","080412","fanghi di adesivi e sigillanti, diversi da quelli di cui alla voce 08 04 11"],
["cer","080413","*fanghi acquosi contenenti adesivi e sigillanti, contenenti solventi organici o altre sostanze pericolose"],
["cer","080414","fanghi acquosi contenenti adesivi e sigillanti, diversi da quelli di cui alla voce 08 04 13"],
["cer","080415","*rifiuti liquidi acquosi contenenti adesivi e sigillanti, contenenti solventi organici o altre sostanze pericolose"],
["cer","080416","rifiuti liquidi acquosi contenenti adesivi e sigillanti, diversi da quelli di cui alla voce 08 04 15"],
["cer","080417","*olio di resina"],
["cer","080499","rifiuti non specificati altrimenti"],
["cer","080500","rifiuti non specificati altrimenti alla voce 08"],
["cer","080501","*isocianati di scarto"],
["cer","090000","RIFIUTI DELL'INDUSTRIA FOTOGRAFICA"],
["cer","090100","rifiuti dell'industria fotografica"],
["cer","090101","*soluzioni di sviluppo e attivanti a base acquosa"],
["cer","090102","*soluzioni di sviluppo per lastre offset a base acquosa"],
["cer","090103","*soluzioni di sviluppo a base di solventi"],
["cer","090104","*soluzioni fissative"],
["cer","090105","*soluzioni di lavaggio e soluzioni di arresto-fissaggio"],
["cer","090106","*rifiuti contenenti argento prodotti dal trattamento in loco di rifiuti fotografici"],
["cer","090107","carta e pellicole per fotografia, contenenti argento o composti dell'argento"],
["cer","090108","carta e pellicole per fotografia, non contenenti argento o composti dell'argento"],
["cer","090110","macchine fotografiche monouso senza batterie"],
["cer","090111","*macchine fotografiche monouso contenenti batterie incluse nelle voci 16 06 01, 16 06 02 o 16 06 03"],
["cer","090112","macchine fotografiche monouso diverse da quelle di cui alla voce 09 01 11"],
["cer","090113","*rifiuti liquidi acquosi prodotti dal recupero in loco dell'argento, diversi da quelli di cui alla voce 09 01 06"],
["cer","090199","rifiuti non specificati altrimenti"],
["cer","100000","RIFIUTI PRODOTTI DA PROCESSI TERMICI"],
["cer","100100","rifiuti prodotti da centrali termiche ed altri impianti termici (tranne 19)"],
["cer","100101"," ceneri pesanti, scorie e polveri di caldaia (tranne le polveri di caldaia di cui alla voce 10 01 04)"],
["cer","100102","ceneri leggere di carbone"],
["cer","100103","ceneri leggere di torba e di legno non trattato"],
["cer","100104","*ceneri leggere di olio combustibile e polveri di caldaia"],
["cer","100105","rifiuti solidi prodotti da reazioni a base di calcio nei processi di desolforazione dei fumi"],
["cer","100107","rifiuti fangosi prodotti da reazioni a base di calcio nei processi di desolforazione dei fumi"],
["cer","100109","*acido solforico"],
["cer","100113","*ceneri leggere prodotte da idrocarburi emulsionati usati come carburante"],
["cer","100114","*ceneri pesanti, scorie e polveri di caldaia prodotte dal coincenerimento, contenenti sostanze pericolose"],
["cer","100115"," ceneri pesanti, scorie e polveri di caldaia prodotte dal coincenerimento, diverse da quelli di cui alla voce 10 01 14"],
["cer","100116","*ceneri leggere prodotte dal coincenerimento, contenenti sostanze pericolose"],
["cer","100117","ceneri leggere prodotte dal coincenerimento, diverse da quelle di cui alla voce 10 01 16"],
["cer","100118","*rifiuti prodotti dalla depurazione dei fumi, contenenti sostanze pericolose"],
["cer","100119","rifiuti prodotti dalla depurazione dei fumi, diversi da quelli di cui alle voci 10 01 05, 10 01 07 e 10 01 18"],
["cer","100120","*fanghi prodotti dal trattamento in loco degli effluenti, contenenti sostanze pericolose"],
["cer","100121","fanghi prodotti dal trattamento in loco degli effluenti, diversi da quelli di cui alla voce 10 01 20"],
["cer","100122","*fanghi acquosi da operazioni di pulizia caldaie, contenenti sostanze pericolose"],
["cer","100123","fanghi acquosi da operazioni di pulizia caldaie, diversi da quelli di cui alla voce 10 01 22"],
["cer","100124","sabbie dei reattori a letto fluidizzato"],
["cer","100125","rifiuti dell'immagazzinamento e della preparazione del combustibile delle centrali termoelettriche a carbone"],
["cer","100126","rifiuti prodotti dal trattamento delle acque di raffreddamento"],
["cer","100199","rifiuti non specificati altrimenti"],
["cer","100200","rifiuti dell'industria siderurgica"],
["cer","100201","rifiuti del trattamento delle scorie"],
["cer","100202","scorie non trattate"],
["cer","100207","*rifiuti solidi prodotti dal trattamento dei fumi, contenenti sostanze pericolose"],
["cer","100208","rifiuti prodotti dal trattamento dei fumi, diversi da quelli di cui alla voce 10 02 07"],
["cer","100210","scaglie di laminazione"],
["cer","100211","*rifiuti prodotti dal trattamento delle acque di raffreddamento, contenti oli"],
["cer","100212","rifiuti prodotti dal trattamento delle acque di raffreddamento, diversi da quelli di cui alla voce 10 02 11"],
["cer","100213","*fanghi e residui di filtrazione prodotti dal trattamento dei fumi, contenenti sostanze pericolose"],
["cer","100214","fanghi e residui di filtrazione prodotti dal trattamento dei fumi, diversi da quelli di cui alla voce 10 02 13"],
["cer","100215","altri fanghi e residui di filtrazione"],
["cer","100299","rifiuti non specificati altrimenti"],
["cer","100300","rifiuti della metallurgia termica dell'alluminio"],
["cer","100302","frammenti di anodi"],
["cer","100304","*scorie della produzione primaria"],
["cer","100305","rifiuti di allumina"],
["cer","100308","*scorie saline della produzione secondaria"],
["cer","100309","*scorie nere della produzione secondaria"],
["cer","100315","*schiumature infiammabili o che rilasciano, al contatto con l'acqua, gas infiammabili in quantità pericolose"],
["cer","100316","schiumature diverse da quelle di cui alla voce 10 03 15"],
["cer","100317","*rifiuti contenenti catrame della produzione degli anodi"],
["cer","100318","rifiuti contenenti carbone della produzione degli anodi, diversi da quelli di cui alla voce 10 03 17"],
["cer","100319","*polveri dei gas di combustione, contenenti sostanze pericolose"],
["cer","100320","polveri dei gas di combustione, diverse da quelle di cui alla voce 10 03 19"],
["cer","100321","*altre polveri e particolati (comprese quelle prodotte da mulini a palle), contenenti sostanze pericolose"],
["cer","100322","altre polveri e particolati (comprese quelle prodotte da mulini a palle), diverse da quelle di cui alla voce 10 03 21"],
["cer","100323","*rifiuti solidi prodotti dal trattamento dei fumi, contenenti sostanze pericolose"],
["cer","100324","rifiuti prodotti dal trattamento dei fumi, diversi da quelli di cui alla voce 10 03 23"],
["cer","100325","*fanghi e residui di filtrazione prodotti dal trattamento dei fumi, contenenti sostanze pericolose"],
["cer","100326","fanghi e residui di filtrazione prodotti dal trattamento dei fumi, diversi da quelli di cui alla voce 10 03 25"],
["cer","100327","*rifiuti prodotti dal trattamento delle acque di raffreddamento, contenenti oli"],
["cer","100328","rifiuti prodotti dal trattamento delle acque di raffreddamento, diversi da quelli di cui alla voce 10 03 27"],
["cer","100329","*rifiuti prodotti dal trattamento di scorie saline e scorie nere, contenenti sostanze pericolose"],
["cer","100330","rifiuti prodotti dal trattamento di scorie saline e scorie nere, diversi da quelli di cui alla voce 10 03 29"],
["cer","100399","rifiuti non specificati altrimenti"],
["cer","100400","rifiuti della metallurgia termica del piombo"],
["cer","100401","*scorie della produzione primaria e secondaria"],
["cer","100402","*scorie e schiumature della produzione primaria e secondaria"],
["cer","100403","*arsenato di calcio"],
["cer","100404","*polveri dei gas di combustione"],
["cer","100405","*altre polveri e particolato"],
["cer","100406","*rifiuti solidi prodotti dal trattamento dei fumi"],
["cer","100407","*fanghi e residui di filtrazione prodotti dal trattamento dei fumi"],
["cer","100409","*rifiuti prodotti dal trattamento delle acque di raffreddamento, contenenti oli"],
["cer","100410","rifiuti prodotti dal trattamento delle acque di raffreddamento, diversi da quelli di cui alla voce 10 04 09"],
["cer","100499","rifiuti non specificati altrimenti"],
["cer","100500","rifiuti della metallurgia termica dello zinco"],
["cer","100501","scorie della produzione primaria e secondaria"],
["cer","100503","*polveri dei gas di combustione"],
["cer","100504","altre polveri e particolato"],
["cer","100505","*rifiuti solidi prodotti dal trattamento dei fumi"],
["cer","100506","*fanghi e residui di filtrazione prodotti dal trattamento dei fumi"],
["cer","100508","*rifiuti prodotti dal trattamento delle acque di raffreddamento, contenenti oli"],
["cer","100509","rifiuti prodotti dal trattamento delle acque di raffreddamento, diversi da quelli di cui alla voce 10 05 08"],
["cer","100510","*scorie e schiumature infiammabili o che rilasciano, al contatto con l'acqua, gas infiammabili in quantità pericolose"],
["cer","100511","scorie e schiumature diverse da quelle di cui alla voce 10 05 10"],
["cer","100599","rifiuti non specificati altrimenti"],
["cer","100600","rifiuti della metallurgia termica del rame"],
["cer","100601","scorie della produzione primaria e secondaria"],
["cer","100602","Scorie e schiumature della produzione primaria e secondaria"],
["cer","100603","*polveri dei gas di combustione"],
["cer","100604","altre polveri e particolato"],
["cer","100606","*rifiuti solidi prodotti dal trattamento dei fumi"],
["cer","100607","*fanghi e residui di filtrazione prodotti dal trattamento dei fumi"],
["cer","100609","*rifiuti prodotti dal trattamento delle acque di raffreddamento, contenenti oli"],
["cer","100610","rifiuti prodotti dal trattamento delle acque di raffreddamento, diversi da quelli di cui alla voce 10 06 09"],
["cer","100699","rifiuti non specificati altrimenti"],
["cer","100700","rifiuti della metallurgia termica di argento, oro e platino"],
["cer","100701","scorie della produzione primaria e secondaria"],
["cer","100702","scorie e schiumature della produzione primaria e secondaria"],
["cer","100703","rifiuti solidi prodotti dal trattamento dei fumi"],
["cer","100704","altre polveri e particolato"],
["cer","100705","fanghi e residui di filtrazione prodotti dal trattamento dei fumi"],
["cer","100707","*rifiuti prodotti dal trattamento delle acque di raffreddamento, contenenti oli"],
["cer","100708","rifiuti prodotti dal trattamento delle acque di raffreddamento, diversi da quelli di cui alla voce 10 07 07"],
["cer","100799","rifiuti non specificati altrimenti"],
["cer","100800","rifiuti della metallurgia termica di altri minerali non ferrosi"],
["cer","100804","polveri e particolato"],
["cer","100808","*scorie salate della produzione primaria e secondaria"],
["cer","100809","altre scorie"],
["cer","100810","*scorie e schiumature infiammabili o che rilasciano, al contatto con l'acqua, gas infiammabili in quantità pericolose"],
["cer","100811","impurità e schiumature diverse da quelle di cui alla voce 10 08 10"],
["cer","100812","*rifiuti contenenti catrame derivante dalla produzione degli anodi"],
["cer","100813","rifiuti contenenti carbonio derivanti dalla produzione di anodi, diversi da quelli di cui alla voce 10 08 12"],
["cer","100814","frammenti di anodi"],
["cer","100815","*polveri dei gas di combustione, contenenti sostanze pericolose"],
["cer","100816","polveri dei gas di combustione, diverse da quelle di cui alla voce 10 08 15"],
["cer","100817","*fanghi e residui di filtrazione prodotti dal trattamento dei fumi, contenenti sostanze pericolose"],
["cer","100818","fanghi e residui di filtrazione prodotti dal trattamento dei fumi, diversi da quelli di cui alla voce 10 08 17"],
["cer","100819","*rifiuti prodotti dal trattamento delle acque di raffreddamento, contenenti oli"],
["cer","100820","rifiuti prodotti dal trattamento delle acque di raffreddamento, diversi da quelli di cui alla voce 10 08 19"],
["cer","100899","rifiuti non specificati altrimenti"],
["cer","100900","rifiuti della fusione di materiali ferrosi"],
["cer","100903","scorie di fusione"],
["cer","100905","*forme e anime da fonderia non utilizzate, contenenti sostanze pericolose"],
["cer","100906","forme e anime da fonderia non utilizzate, diverse da quelle di cui alla voce 10 09 05"],
["cer","100907","*forme e anime da fonderia utilizzate, contenenti sostanze pericolose"],
["cer","100908","forme e anime da fonderia utilizzate, diverse da quelle di cui alla voce 10 09 07"],
["cer","100909","*polveri dei gas di combustione contenenti sostanze pericolose"],
["cer","100910","polveri dei gas di combustione diverse da quelle di cui alla voce 10 09 09"],
["cer","100911","*altri particolati contenenti sostanze pericolose"],
["cer","100912","altri particolati diversi da quelli di cui alla voce 10 09 11"],
["cer","100913","*scarti di leganti contenenti sostanze pericolose"],
["cer","100914","scarti di leganti diversi da quelli di cui alla voce 10 09 13"],
["cer","100915","*scarti di prodotti rilevatori di crepe, contenenti sostanze pericolose"],
["cer","100916","scarti di prodotti rilevatori di crepe, diversi da quelli di cui alla voce 10 09 15"],
["cer","100999","rifiuti non specificati altrimenti"],
["cer","101000","rifiuti della fusione di materiali non ferrosi"],
["cer","101003","scorie di fusione"],
["cer","101005","*forme e anime da fonderia non utilizzate, contenenti sostanze pericolose"],
["cer","101006","forme e anime da fonderia non utilizzate, diverse da quelle di cui alla voce 10 10 05"],
["cer","101007","*forme e anime da fonderia utilizzate, contenenti sostanze pericolose"],
["cer","101008","forme e anime da fonderia utilizzate, diverse da quelle di cui alla voce 10 10 07"],
["cer","101009","*polveri dei gas di combustione, contenenti sostanze pericolose"],
["cer","101010","polveri dei gas di combustione, diverse da quelle di cui alla voce 10 10 09"],
["cer","101011","*altri particolati contenenti sostanze pericolose"],
["cer","101012","altri particolati diversi da quelli di cui alla voce 10 10 11"],
["cer","101013","*scarti di leganti contenenti sostanze pericolose"],
["cer","101014","scarti di leganti diversi da quelli di cui alla voce 10 10 13"],
["cer","101015","*scarti di prodotti rilevatori di crepe, contenenti sostanze pericolose"],
["cer","101016","scarti di prodotti rilevatori di crepe, diversi da quelli di cui alla voce 10 10 15"],
["cer","101099","rifiuti non specificati altrimenti"],
["cer","101100","rifiuti della fabbricazione del vetro e di prodotti di vetro"],
["cer","101103","scarti di materiali in fibra a base di vetro"],
["cer","101105","polveri e particolato"],
["cer","101109","*residui di miscela di preparazione non sottoposti a trattamento termico, contenenti sostanze pericolose"],
["cer","101110","residui di miscela di preparazione non sottoposti a trattamento termico, diverse da quelle di cui alla voce 10 11 09"],
["cer","101111","*rifiuti di vetro in forma di particolato e polveri di vetro contenenti metalli pesanti (provenienti ad es. da tubi a raggi catodici)"],
["cer","101112","rifiuti di vetro diversi da quelli di cui alla voce 10 11 11"],
["cer","101113","*fanghi provenienti dalla lucidatura e dalla macinazione del vetro, contenenti sostanze pericolose"],
["cer","101114","fanghi provenienti dalla lucidatura e dalla macinazione del vetro, diversi da quelli di cui alla voce 10 11 13"],
["cer","101115","*rifiuti solidi prodotti dal trattamento dei fumi, contenenti sostanze pericolose"],
["cer","101116","rifiuti prodotti dal trattamento dei fumi, diversi da quelli di cui alla voce 10 11 15"],
["cer","101117","*fanghi e residui di filtrazione prodotti dal trattamento dei fumi, contenenti sostanze pericolose"],
["cer","101118","fanghi e residui di filtrazione prodotti dal trattamento dei fumi, diversi da quelli di cui alla voce 10 11 17"],
["cer","101119","*rifiuti solidi prodotti dal trattamento in loco degli effluenti, contenenti sostanze pericolose"],
["cer","101120","rifiuti solidi prodotti dal trattamento in loco degli effluenti, diversi da quelli di cui alla voce 10 11 19"],
["cer","101199","rifiuti non specificati altrimenti"],
["cer","101200","rifiuti della fabbricazione di prodotti di ceramica, mattoni, mattonelle e materiali da costruzione"],
["cer","101201","residui di miscela di preparazione non sottoposti a trattamento termico"],
["cer","101203","polveri e particolato"],
["cer","101205","fanghi e residui di filtrazione prodotti dal trattamento dei fumi"],
["cer","101206","stampi di scarto"],
["cer","101208","scarti di ceramica, mattoni, mattonelle e materiali da costruzione (sottoposti a trattamento termico)"],
["cer","101209","*rifiuti solidi prodotti dal trattamento dei fumi, contenenti sostanze pericolose"],
["cer","101210","rifiuti solidi prodotti dal trattamento dei fumi, diversi da quelli di cui alla voce 10 12 09"],
["cer","101211","*rifiuti delle operazioni di smaltatura, contenenti metalli pesanti"],
["cer","101212","rifiuti delle operazioni di smaltatura diversi da quelli di cui alla voce 10 12 11"],
["cer","101213","fanghi prodotti dal trattamento in loco degli effluenti"],
["cer","101299","rifiuti non specificati altrimenti"],
["cer","101300","rifiuti della fabbricazione di cemento, calce e gesso e manufatti di tali materiali"],
["cer","101301","residui di miscela di preparazione non sottoposti a trattamento termico"],
["cer","101304","rifiuti di calcinazione e di idratazione della calce"],
["cer","101306","polveri e particolato (eccetto quelli delle voci 10 13 12 e 10 13 13)"],
["cer","101307","fanghi e residui di filtrazione prodotti dal trattamento dei fumi"],
["cer","101309","*rifiuti della fabbricazione di amianto cemento, contenenti amianto"],
["cer","101310","rifiuti della fabbricazione di amianto cemento, diversi da quelli di cui alla voce 10 13 09"],
["cer","101311","rifiuti della produzione di materiali compositi a base di cemento, diversi da quelli di cui alle voci 10 13 09 e 10 13 10"],
["cer","101312","*rifiuti solidi prodotti dal trattamento dei fumi, contenenti sostanze pericolose"],
["cer","101313","rifiuti solidi prodotti dal trattamento dei fumi, diversi da quelli di cui alla voce 10 13 12"],
["cer","101314","rifiuti e fanghi di cemento"],
["cer","101399","rifiuti non specificati altrimenti"],
["cer","101400","rifiuti prodotti dai forni crematori"],
["cer","101401","*rifiuti prodotti dalla depurazione dei fumi, contenenti mercurio"],
["cer","110000","RIFIUTI PRODOTTI DAL TRATTAMENTO CHIMICO SUPERFICIALE E DAL RIVESTIMENTO DI METALLI ED ALTRI MATERIALI; IDROMETALLURGIA NON FERROSA"],
["cer","110100","rifiuti prodotti dal trattamento e ricopertura di metalli (ad esempio, processi galvanici, zincatura, decapaggio, pulitura elettrolitica, fosfatazione, sgrassaggio con alcali, anodizzazione)"],
["cer","110105","*acidi di decappaggio"],
["cer","110106","*acidi non specificati altrimenti"],
["cer","110107","*basi di decappaggio"],
["cer","110108","*fanghi di fosfatazione"],
["cer","110109","*fanghi e residui di filtrazione, contenenti sostanze pericolose"],
["cer","110110","fanghi e residui di filtrazione, diversi da quelli di cui alla voce 11 01 09"],
["cer","110111","*soluzioni acquose di lavaggio, contenenti sostanze pericolose"],
["cer","110112","soluzioni acquose di lavaggio, diverse da quelle di cui alla voce 11 01 11"],
["cer","110113","*rifiuti di sgrassaggio contenenti sostanze pericolose"],
["cer","110114","rifiuti di sgrassaggio diversi da quelli di cui alla voce 11 01 13"],
["cer","110115","*eluati e fanghi di sistemi a membrana e sistemi a scambio ionico, contenenti sostanze pericolose"],
["cer","110116","*resine a scambio ionico saturate o esaurite"],
["cer","110198","*altri rifiuti contenenti sostanze pericolose"],
["cer","110199","rifiuti non specificati altrimenti"],
["cer","110200","rifiuti prodotti dalla lavorazione idrometallurgica di metalli non ferrosi"],
["cer","110202","*rifiuti della lavorazione idrometallurgica dello zinco (compresi jarosite, goethite)"],
["cer","110203","rifiuti della produzione di anodi per processi elettrolitici acquosi"],
["cer","110205","*rifiuti della lavorazione idrometallurgica del rame, contenenti sostanze pericolose"],
["cer","110206","rifiuti della lavorazione idrometallurgica del rame, diversi da quelli della voce 11 02 05"],
["cer","110207","*altri rifiuti contenenti sostanze pericolose"],
["cer","110299","rifiuti non specificati altrimenti"],
["cer","110300","rifiuti solidi e fanghi prodotti da processi di rinvenimento"],
["cer","110301","*rifiuti contenenti cianuro"],
["cer","110302","*altri rifiuti"],
["cer","110500","rifiuti prodotti da processi di galvanizzazione a caldo"],
["cer","110501","zinco solido"],
["cer","110502","ceneri di zinco"],
["cer","110503","*rifiuti solidi prodotti dal trattamento dei fumi"],
["cer","110504","*fondente esaurito"],
["cer","110599","rifiuti non specificati altrimenti"],
["cer","120000","RIFIUTI PRODOTTI DALLA LAVORAZIONE E DAL TRATTAMENTO FISICO E MECCANICO SUPERFICIALE DI METALLI E PLASTICA"],
["cer","120100","rifiuti prodotti dalla lavorazione e dal trattamento fisico e meccanico superficiale di metalli e plastiche"],
["cer","120101","limatura e trucioli di materiali ferrosi"],
["cer","120102","polveri e particolato di materiali ferrosi"],
["cer","120103","limatura, scaglie e polveri di metalli non ferrosi"],
["cer","120104","polveri e particolato di materiali non ferrosi"],
["cer","120105","limatura e trucioli di materiali plastici"],
["cer","120106","*oli minerali per macchinari, contenenti alogeni (eccetto emulsioni e soluzioni)"],
["cer","120107","*oli minerali per macchinari, non contenenti alogeni (eccetto emulsioni e soluzioni)"],
["cer","120108","*emulsioni e soluzioni per macchinari, contenenti alogeni"],
["cer","120109","*emulsioni e soluzioni per macchinari, non contenenti alogeni"],
["cer","120110","*oli sintetici per macchinari"],
["cer","120112","*cere e grassi esauriti"],
["cer","120113","rifiuti di saldatura"],
["cer","120114","*fanghi di lavorazione, contenenti sostanze pericolose"],
["cer","120115","fanghi di lavorazione, diversi da quelli di cui alla voce 12 01 14"],
["cer","120116","*residui di materiale di sabbiatura, contenente sostanze pericolose"],
["cer","120117","residui di materiale di sabbiatura, diversi da quelli di cui alla voce 12 01 16"],
["cer","120118","*fanghi metallici (fanghi di rettifica, affilatura e lappatura) contenenti olio"],
["cer","120119","*oli per macchinari, facilmente biodegradabili"],
["cer","120120","*corpi d'utensile e materiali di rettifica esauriti, contenenti sostanze pericolose"],
["cer","120121","corpi d'utensile e materiali di rettifica esauriti, diversi da quelli di cui alla voce 12 01 20"],
["cer","120199","rifiuti non specificati altrimenti"],
["cer","120300","rifiuti prodotti da processi di sgrassatura ad acqua e vapore (tranne 11)"],
["cer","120301","*soluzioni acquose di lavaggio"],
["cer","120302","*rifiuti prodotti da processi di sgrassatura a vapore"],
["cer","130000","OLI ESAURITI E RESIDUI DI COMBUSTIBILI LIQUIDI (tranne oli commestibili ed oli di cui ai capitoli 05, 12 e 19)"],
["cer","130100","scarti di oli per circuiti idraulici"],
["cer","130101","*oli per circuiti idraulici contenenti PCB (La definizione di PCB adottata nel presente elenco di rifiuti è quella contenuta nella direttiva 96/59/CE.)"],
["cer","130104","*emulsioni clorurate"],
["cer","130105","*emulsioni non clorurate"],
["cer","130109","*oli minerali per circuiti idraulici, clorurati"],
["cer","130110","*oli minerali per circuiti idraulici, non clorurati"],
["cer","130111","*oli sintetici per circuiti idraulici"],
["cer","130112","*oli per circuiti idraulici, facilmente biodegradabili"],
["cer","130113","*altri oli per circuiti idraulici"],
["cer","130200","scarti di olio motore, olio per ingranaggi e oli lubrificanti"],
["cer","130204","*oli minerali per motori, ingranaggi e lubrificazione, clorurati"],
["cer","130205","*oli minerali per motori, ingranaggi e lubrificazione, non clorurati"],
["cer","130206","*oli sintetici per motori, ingranaggi e lubrificazione"],
["cer","130207","*olio per motori, ingranaggi e lubrificazione, facilmente biodegradabile"],
["cer","130208","*altri oli per motori, ingranaggi e lubrificazione"],
["cer","130300","oli isolanti e oli termoconduttori usati"],
["cer","130301","*oli isolanti e termoconduttori, contenenti PCB"],
["cer","130306","*oli minerali isolanti e termoconduttori clorurati, diversi da quelli di cui alla voce 13 03 01"],
["cer","130307","*oli minerali isolanti e termoconduttori non clorurati"],
["cer","130308","*oli sintetici isolanti e termoconduttori"],
["cer","130309","*oli isolanti e termoconduttori, facilmente biodegradabili"],
["cer","130310","*altri oli isolanti e termoconduttori"],
["cer","130400","oli di sentina"],
["cer","130401","*oli di sentina della navigazione interna"],
["cer","130402","*oli di sentina delle fognature dei moli"],
["cer","130403","*altri oli di sentina della navigazione"],
["cer","130500","prodotti di separazione olio/acqua"],
["cer","130501","*rifiuti solidi delle camere a sabbia e di prodotti di separazione olio/acqua"],
["cer","130502","*fanghi di prodotti di separazione olio/acqua"],
["cer","130503","*fanghi da collettori"],
["cer","130506","*oli prodotti dalla separazione olio/acqua"],
["cer","130507","*acque oleose prodotte dalla separazione olio/acqua"],
["cer","130508","*miscugli di rifiuti delle camere a sabbia e dei prodotti di separazione olio/acqua"],
["cer","130700","residui di combustibili liquidi"],
["cer","130701","*olio combustibile e carburante diesel"],
["cer","130702","*benzina"],
["cer","130703","*altri carburanti (comprese le miscele)"],
["cer","130800","rifiuti di oli non specificati altrimenti"],
["cer","130801","*fanghi ed emulsioni prodotti dai processi di dissalazione"],
["cer","130802","*altre emulsioni"],
["cer","130899","*rifiuti non specificati altrimenti"],
["cer","140000","SOLVENTI ORGANICI, REFRIGERANTI E PROPELLENTI DI SCARTO (tranne 07 e 08)"],
["cer","140600","rifiuti di solventi organici, refrigeranti e propellenti di schiuma/aerosol"],
["cer","140601","*clorofluorocarburi, HCFC, HFC1"],
["cer","140602","*altri solventi e miscele di solventi, alogenati"],
["cer","140603","*altri solventi e miscele di solventi"],
["cer","140604","*fanghi o rifiuti solidi, contenenti solventi alogenati"],
["cer","140605","*fanghi o rifiuti solidi, contenenti altri solventi"],
["cer","150000","RIFIUTI DI IMBALLAGGIO, ASSORBENTI, STRACCI, MATERIALI FILTRANTI E INDUMENTI PROTETTIVI (NON SPECIFICATI ALTRIMENTI)"],
["cer","150100","imballaggi (compresi i rifiuti urbani di imballaggio oggetto di raccolta differenziata)"],
["cer","150101","imballaggi in carta e cartone"],
["cer","150102","imballaggi in plastica"],
["cer","150103","imballaggi in legno"],
["cer","150104","imballaggi metallici"],
["cer","150105","imballaggi compositi"],
["cer","150106","imballaggi in materiali misti"],
["cer","150107","imballaggi in vetro"],
["cer","150109","imballaggi in materia tessile"],
["cer","150110","*imballaggi contenenti residui di sostanze pericolose o contaminati da tali sostanze"],
["cer","150111","*imballaggi metallici contenenti matrici solide porose pericolose (ad esempio amianto), compresi i contenitori a pressione vuoti"],
["cer","150200","assorbenti, materiali filtranti, stracci e indumenti protettivi"],
["cer","150202","*assorbenti, materiali filtranti (inclusi filtri dell'olio non specificati altrimenti), stracci e indumenti protettivi, contaminati da sostanze pericolose"],
["cer","150203","assorbenti, materiali filtranti, stracci e indumenti protettivi, diversi da quelli di cui alla voce 15 02 02"],
["cer","160000","RIFIUTI NON SPECIFICATI ALTRIMENTI NELL'ELENCO"],
["cer","160100","veicoli fuori uso appartenenti a diversi modi di trasporto (comprese le macchine mobili non stradali) e rifiuti prodotti dallo smantellamento di veicoli fuori uso e dalla manutenzione di veicoli (tranne 13, 14, 16 06 e 16 08)"],
["cer","160103","pneumatici fuori uso"],
["cer","160104","*veicoli fuori uso"],
["cer","160106","veicoli fuori uso, non contenenti liquidi né altre componenti pericolose"],
["cer","160107","*filtri dell'olio"],
["cer","160108","*componenti contenenti mercurio"],
["cer","160109","*componenti contenenti PCB"],
["cer","160110","*componenti esplosivi (ad esempio 'air bag')"],
["cer","160111","*pastiglie per freni, contenenti amianto"],
["cer","160112","pastiglie per freni, diverse da quelle di cui alla voce 16 01 11"],
["cer","160113","*liquidi per freni"],
["cer","160114","*liquidi antigelo contenenti sostanze pericolose"],
["cer","160115","liquidi antigelo diversi da quelli di cui alla voce 16 01 14"],
["cer","160116","serbatoi per gas liquido"],
["cer","160117","metalli ferrosi"],
["cer","160118","metalli non ferrosi"],
["cer","160119","plastica"],
["cer","160120","vetro"],
["cer","160121","*componenti pericolosi diversi da quelli di cui alle voci da 16 01 07 a 16 01 11, 16 01 13 e 16 01 14"],
["cer","160122","componenti non specificati altrimenti"],
["cer","160199","rifiuti non specificati altrimenti"],
["cer","160200","rifiuti provenienti da apparecchiature elettriche ed elettroniche"],
["cer","160209","*trasformatori e condensatori contenenti PCB"],
["cer","160210","*apparecchiature fuori uso contenenti PCB o da essi contaminate, diverse da quelle di cui alla voce 16 02 09"],
["cer","160211","*apparecchiature fuori uso, contenenti clorofluorocarburi, HCFC, HFC"],
["cer","160212","*apparecchiature fuori uso, contenenti amianto in fibre libere"],
["cer","160213","*apparecchiature fuori uso, contenenti componenti pericolosi (2) diversi da quelli di cui alle voci 16 02 09 e 16 02 12"],
["cer","160214","apparecchiature fuori uso, diverse da quelle di cui alle voci da 16 02 09 a 16 02 13"],
["cer","160215","*componenti pericolosi rimossi da apparecchiature fuori uso"],
["cer","160216","componenti rimossi da apparecchiature fuori uso, diversi da quelli di cui alla voce 16 02 15"],
["cer","160300","prodotti fuori specifica e prodotti inutilizzati"],
["cer","160303","*rifiuti inorganici, contenenti sostanze pericolose"],
["cer","160304","rifiuti inorganici, diversi da quelli di cui alla voce 16 03 03"],
["cer","160305","*rifiuti organici, contenenti sostanze pericolose"],
["cer","160306","rifiuti organici, diversi da quelli di cui alla voce 16 03 05"],
["cer","160307","*mercurio metallico (nuovo codice CER)"],
["cer","160400","esplosivi di scarto"],
["cer","160401","*munizioni di scarto"],
["cer","160402","*fuochi artificiali di scarto"],
["cer","160403","*altri esplosivi di scarto"],
["cer","160500","gas in contenitori a pressione e prodotti chimici di scarto"],
["cer","160504","*gas in contenitori a pressione (compresi gli halon), contenenti sostanze pericolose"],
["cer","160505","gas in contenitori a pressione, diversi da quelli di cui alla voce 16 05 04"],
["cer","160506","*sostanze chimiche di laboratorio contenenti o costituite da sostanze pericolose, comprese le miscele di sostanze chimiche di laboratorio"],
["cer","160507","*sostanze chimiche inorganiche di scarto contenenti o costituite da sostanze pericolose"],
["cer","160508","*sostanze chimiche organiche di scarto contenenti o costituite da sostanze pericolose"],
["cer","160509","sostanze chimiche di scarto diverse da quelle di cui alle voci 16 05 06, 16 05 07 e 16 05 08"],
["cer","160600","batterie ed accumulatori"],
["cer","160601","*batterie al piombo"],
["cer","160602","*batterie al nichel-cadmio"],
["cer","160603","*batterie contenenti mercurio"],
["cer","160604","batterie alcaline (tranne 16 06 03)"],
["cer","160605","altre batterie ed accumulatori"],
["cer","160606","*elettroliti di batterie ed accumulatori, oggetto di raccolta differenziata"],
["cer","160700","rifiuti della pulizia di serbatoi per trasporto e stoccaggio e di fusti (tranne 05 e 13)"],
["cer","160708","*rifiuti contenenti olio"],
["cer","160709","*rifiuti contenenti altre sostanze pericolose"],
["cer","160799","rifiuti non specificati altrimenti"],
["cer","160800","catalizzatori esauriti"],
["cer","160801","catalizzatori esauriti contenenti oro, argento, renio, rodio, palladio, iridio o platino (tranne 16 08 07)"],
["cer","160802","*catalizzatori esauriti contenenti metalli di transizione (3) pericolosi o composti di metalli di transizione pericolosi"],
["cer","160803","catalizzatori esauriti contenenti metalli di transizione o composti di metalli di transizione, non specificati altrimenti"],
["cer","160804","catalizzatori esauriti da cracking catalitico fluido (tranne 16 08 07)"],
["cer","160805","*catalizzatori esauriti contenenti acido fosforico"],
["cer","160806","*liquidi esauriti usati come catalizzatori"],
["cer","160807","*catalizzatori esauriti contaminati da sostanze pericolose"],
["cer","160900","sostanze ossidanti"],
["cer","160901","*permanganati, ad esempio permanganato di potassio"],
["cer","160902","*cromati, ad esempio cromato di potassio, dicromato di potassio o di sodio"],
["cer","160903","*perossidi, ad esempio perossido d'idrogeno"],
["cer","160904","*sostanze ossidanti non specificate altrimenti"],
["cer","161000","rifiuti liquidi acquosi destinati ad essere trattati fuori sito"],
["cer","161001","*rifiuti liquidi acquosi, contenenti sostanze pericolose"],
["cer","161002","rifiuti liquidi acquosi, diversi da quelle di cui alla voce 16 10 01"],
["cer","161003","*concentrati acquosi, contenenti sostanze pericolose"],
["cer","161004","concentrati acquosi, diversi da quelli di cui alla voce 16 10 03"],
["cer","161100","scarti di rivestimenti e materiali refrattari"],
["cer","161101","*rivestimenti e materiali refrattari a base di carbone provenienti da processi metallurgici, contenenti sostanze pericolose"],
["cer","161102","rivestimenti e materiali refrattari a base di carbone provenienti dalle lavorazioni metallurgiche, diversi da quelli di cui alla voce 16 11 01"],
["cer","161103","*altri rivestimenti e materiali refrattari provenienti da processi metallurgici, contenenti sostanze pericolose"],
["cer","161104","altri rivestimenti e materiali refrattari provenienti da processi metallurgici, diversi da quelli di cui alla voce 16 11 03"],
["cer","161105","*rivestimenti e materiali refrattari provenienti da lavorazioni non metallurgiche, contenenti sostanze pericolose"],
["cer","161106","rivestimenti e materiali refrattari provenienti da lavorazioni non metallurgiche, diversi da quelli di cui alla voce 16 11 05"],
["cer","170000","RIFIUTI DELLE OPERAZIONI DI COSTRUZIONE E DEMOLIZIONE (COMPRESO IL TERRENO PROVENIENTE DA SITI CONTAMINATI)"],
["cer","170100","cemento, mattoni, mattonelle e ceramiche"],
["cer","170101","cemento"],
["cer","170102","mattoni"],
["cer","170103","mattonelle e ceramiche"],
["cer","170106","*miscugli o frazioni separate di cemento, mattoni, mattonelle e ceramiche, contenenti sostanze pericolose"],
["cer","170107","miscugli o frazioni separate di cemento, mattoni, mattonelle e ceramiche, diverse da quelle di cui alla voce 17 01 06"],
["cer","170200","legno, vetro e plastica"],
["cer","170201","legno"],
["cer","170202","vetro"],
["cer","170203","plastica"],
["cer","170204","*vetro, plastica e legno contenenti sostanze pericolose o da esse contaminati"],
["cer","170300","miscele bituminose, catrame di carbone e prodotti contenenti catrame"],
["cer","170301","*miscele bituminose contenenti catrame di carbone"],
["cer","170302","miscele bituminose diverse da quelle di cui alla voce 17 03 01"],
["cer","170303","*catrame di carbone e prodotti contenenti catrame"],
["cer","170400","metalli (incluse le loro leghe)"],
["cer","170401","rame, bronzo, ottone"],
["cer","170402","alluminio"],
["cer","170403","piombo"],
["cer","170404","zinco"],
["cer","170405","ferro e acciaio"],
["cer","170406","stagno"],
["cer","170407","metalli misti"],
["cer","170409","*rifiuti metallici contaminati da sostanze pericolose"],
["cer","170410","*cavi, impregnati di olio, di catrame di carbone o di altre sostanze pericolose"],
["cer","170411","cavi, diversi da quelli di cui alla voce 17 04 10"],
["cer","170500","terra (compresa quella proveniente da siti contaminati), rocce e materiale di dragaggio"],
["cer","170503","*terra e rocce, contenenti sostanze pericolose"],
["cer","170504","terra e rocce, diverse da quelle di cui alla voce 17 05 03"],
["cer","170505","*fanghi di dragaggio, contenente sostanze pericolose"],
["cer","170506","fanghi di dragaggio, diversa da quella di cui alla voce 17 05 05"],
["cer","170507","*pietrisco per massicciate ferroviarie, contenente sostanze pericolose"],
["cer","170508","pietrisco per massicciate ferroviarie, diverso da quello di cui alla voce 17 05 07"],
["cer","170600","materiali isolanti e materiali da costruzione contenenti amianto"],
["cer","170601","*materiali isolanti contenenti amianto"],
["cer","170603","*altri materiali isolanti contenenti o costituiti da sostanze pericolose"],
["cer","170604","materiali isolanti diversi da quelli di cui alle voci 17 06 01 e 17 06 03"],
["cer","170605","*materiali da costruzione contenenti amianto"],
["cer","170800","materiali da costruzione a base di gesso"],
["cer","170801","*materiali da costruzione a base di gesso contaminati da sostanze pericolose"],
["cer","170802","materiali da costruzione a base di gesso diversi da quelli di cui alla voce 17 08 01"],
["cer","170900","altri rifiuti dell'attività di costruzione e demolizione"],
["cer","170901","*rifiuti dell'attività di costruzione e demolizione, contenenti mercurio"],
["cer","170902","*rifiuti dell'attività di costruzione e demolizione, contenenti PCB (ad esempio sigillanti contenenti PCB, pavimentazioni a base di resina contenenti PCB, elementi stagni in vetro contenenti PCB, condensatori contenenti PCB)"],
["cer","170903","*altri rifiuti dell'attività di costruzione e demolizione (compresi rifiuti misti) contenenti sostanze pericolose"],
["cer","170904","rifiuti misti dell'attività di costruzione e demolizione, diversi da quelli di cui alle voci 17 09 01, 17 09 02 e 17 09 03"],
["cer","180000","RIFIUTI PRODOTTI DAL SETTORE SANITARIO E VETERINARIO O DA ATTIVITÀ DI RICERCA COLLEGATE(tranne i rifiuti di cucina e di ristorazione non direttamente provenienti da trattamento terapeutico)"],
["cer","180100","rifiuti dei reparti di maternità e rifiuti legati a diagnosi, trattamento e prevenzione delle malattie negli esseri umani"],
["cer","180101","oggetti da taglio (eccetto 18 01 03)"],
["cer","180102","parti anatomiche ed organi incluse le sacche per il plasma e le riserve di sangue (tranne 18 01 03)"],
["cer","180103","*rifiuti che devono essere raccolti e smaltiti applicando precauzioni particolari per evitare infezioni"],
["cer","180104","rifiuti che non devono essere raccolti e smaltiti applicando precauzioni particolari per evitare infezioni (es. bende, ingessature, lenzuola, indumenti monouso, assorbenti igienici)"],
["cer","180106","*sostanze chimiche pericolose o contenenti sostanze pericolose"],
["cer","180107","sostanze chimiche diverse da quelle di cui alla voce 18 01 06"],
["cer","180108","*medicinali citotossici e citostatici"],
["cer","180109","medicinali diversi da quelli di cui alla voce 18 01 08"],
["cer","180110","*rifiuti di amalgama prodotti da interventi odontoiatrici"],
["cer","180200","rifiuti legati alle attività di ricerca e diagnosi, trattamento e prevenzione delle malattie negli animali"],
["cer","180201","oggetti da taglio (eccetto 18 02 02)"],
["cer","180202","*rifiuti che devono essere raccolti e smaltiti applicando precauzioni particolari per evitare infezioni"],
["cer","180203","rifiuti che non devono essere raccolti e smaltiti applicando precauzioni particolari per evitare infezioni"],
["cer","180205","*sostanze chimiche pericolose o contenenti sostanze pericolose"],
["cer","180206","sostanze chimiche diverse da quelle di cui alla voce 18 02 05"],
["cer","180207","*medicinali citotossici e citostatici"],
["cer","180208","medicinali diversi da quelli di cui alla voce 18 02 07"],
["cer","190000","RIFIUTI PRODOTTI DA IMPIANTI DI TRATTAMENTO DEI RIFIUTI, IMPIANTI DI TRATTAMENTO DELLE ACQUE REFLUE FUORI SITO, NONCHÉ DALLA POTABILIZZAZIONE DELL'ACQUA E DALLA SUA PREPARAZIONE PER USO INDUSTRIALE"],
["cer","190100","rifiuti da incenerimento o pirolisi di rifiuti"],
["cer","190102","materiali ferrosi estratti da ceneri pesanti"],
["cer","190105","*residui di filtrazione prodotti dal trattamento dei fumi"],
["cer","190106","*rifiuti liquidi acquosi prodotti dal trattamento dei fumi e di altri rifiuti liquidi acquosi"],
["cer","190107","*rifiuti solidi prodotti dal trattamento dei fumi"],
["cer","190110","*carbone attivo esaurito, impiegato per il trattamento dei fumi"],
["cer","190111","*ceneri pesanti e scorie, contenenti sostanze pericolose"],
["cer","190112","ceneri pesanti e scorie, diverse da quelle di cui alla voce 19 01 11"],
["cer","190113","*ceneri leggere, contenenti sostanze pericolose"],
["cer","190114","ceneri leggere, diverse da quelle di cui alla voce 19 01 13"],
["cer","190115","*polveri di caldaia, contenenti sostanze pericolose"],
["cer","190116","polveri di caldaia, diverse da quelle di cui alla voce 19 01 15"],
["cer","190117","*rifiuti della pirolisi, contenenti sostanze pericolose"],
["cer","190118","rifiuti della pirolisi, diversi da quelli di cui alla voce 19 01 17"],
["cer","190119","sabbie dei reattori a letto fluidizzato"],
["cer","190199","rifiuti non specificati altrimenti"],
["cer","190200","rifiuti prodotti da specifici trattamenti chimico-fisici di rifiuti industriali (comprese decromatazione, decianizzazione, neutralizzazione)"],
["cer","190203","rifiuti premiscelati composti esclusivamente da rifiuti non pericolosi"],
["cer","190204","*rifiuti premiscelati contenenti almeno un rifiuto pericoloso"],
["cer","190205","*fanghi prodotti da trattamenti chimico-fisici, contenenti sostanze pericolose"],
["cer","190206","fanghi prodotti da trattamenti chimico-fisici, diversi da quelli di cui alla voce 19 02 05"],
["cer","190207","*oli e concentrati prodotti da processi di separazione"],
["cer","190208","*rifiuti combustibili liquidi, contenenti sostanze pericolose"],
["cer","190209","*rifiuti combustibili solidi, contenenti sostanze pericolose"],
["cer","190210","rifiuti combustibili, diversi da quelli di cui alle voci 19 02 08 e 19 02 09"],
["cer","190211","*altri rifiuti contenenti sostanze pericolose"],
["cer","190299","rifiuti non specificati altrimenti"],
["cer","190300","rifiuti stabilizzati/solidificati (4)"],
["cer","190304","*rifiuti contrassegnati come pericolosi, parzialmente (5) stabilizzati"],
["cer","190305","rifiuti stabilizzati diversi da quelli di cui alla voce 19 03 04"],
["cer","190306","*rifiuti contrassegnati come pericolosi, solidificati"],
["cer","190307","rifiuti solidificati diversi da quelli di cui alla voce 19 03 06"],
["cer","190308","*mercurio parzialmente stabilizzato (nuovo codice CER)"],
["cer","190400","rifiuti vetrificati e rifiuti di vetrificazione"],
["cer","190401","rifiuti vetrificati"],
["cer","190402","*ceneri leggere ed altri rifiuti dal trattamento dei fumi"],
["cer","190403","*fase solida non vetrificata"],
["cer","190404","rifiuti liquidi acquosi prodotti dalla tempra di rifiuti vetrificati"],
["cer","190500","rifiuti prodotti dal trattamento aerobico di rifiuti solidi"],
["cer","190501","parte di rifiuti urbani e simili non compostata"],
["cer","190502","parte di rifiuti animali e vegetali non compostata"],
["cer","190503","compost fuori specifica"],
["cer","190599","rifiuti non specificati altrimenti"],
["cer","190600","rifiuti prodotti dal trattamento anaerobico dei rifiuti"],
["cer","190603","liquidi prodotti dal trattamento anaerobico di rifiuti urbani"],
["cer","190604","digestato prodotto dal trattamento anaerobico di rifiuti urbani"],
["cer","190605","liquidi prodotti dal trattamento anaerobico di rifiuti di origine animale o vegetale"],
["cer","190606","digestato prodotto dal trattamento anaerobico di rifiuti di origine animale o vegetale"],
["cer","190699","rifiuti non specificati altrimenti"],
["cer","190700","percolato di discarica"],
["cer","190702","*percolato di discarica, contenente sostanze pericolose"],
["cer","190703","percolato di discarica, diverso da quello di cui alla voce 19 07 02"],
["cer","190800","rifiuti prodotti dagli impianti per il trattamento delle acque reflue, non specificati altrimenti"],
["cer","190801","residui di vagliatura"],
["cer","190802","rifiuti dell'eliminazione della sabbia"],
["cer","190805","fanghi prodotti dal trattamento delle acque reflue urbane"],
["cer","190806","*resine a scambio ionico saturate o esaurite"],
["cer","190807","*soluzioni e fanghi di rigenerazione delle resine a scambio ionico"],
["cer","190808","*rifiuti prodotti da sistemi a membrana, contenenti sostanze pericolose"],
["cer","190809","miscele di oli e grassi prodotte dalla separazione olio/acqua, contenenti esclusivamente oli e grassi commestibili"],
["cer","190810","*miscele di oli e grassi prodotte dalla separazione olio/acqua, diverse da quelle di cui alla voce 19 08 09"],
["cer","190811","*fanghi prodotti dal trattamento biologico delle acque reflue industriali, contenenti sostanze pericolose"],
["cer","190812","fanghi prodotti dal trattamento biologico delle acque reflue industriali, diversi da quelli di cui alla voce 19 08 11"],
["cer","190813","*fanghi contenenti sostanze pericolose prodotti da altri trattamenti delle acque reflue industriali"],
["cer","190814","fanghi prodotti da altri trattamenti delle acque reflue industriali, diversi da quelli di cui alla voce 19 08 13"],
["cer","190899","rifiuti non specificati altrimenti"],
["cer","190900","rifiuti prodotti dalla potabilizzazione dell'acqua o dalla sua preparazione per uso industriale"],
["cer","190901","rifiuti solidi prodotti dai processi di filtrazione e vaglio primari"],
["cer","190902","fanghi prodotti dai processi di chiarificazione dell'acqua"],
["cer","190903","fanghi prodotti dai processi di decarbonatazione"],
["cer","190904","carbone attivo esaurito"],
["cer","190905","resine a scambio ionico saturate o esaurite"],
["cer","190906","soluzioni e fanghi di rigenerazione delle resine a scambio ionico"],
["cer","190999","rifiuti non specificati altrimenti"],
["cer","191000","rifiuti prodotti da operazioni di frantumazione di rifiuti contenenti metallo"],
["cer","191001","rifiuti di ferro e acciaio"],
["cer","191002","rifiuti di metalli non ferrosi"],
["cer","191003","*fluff - frazione leggera e polveri, contenenti sostanze pericolose"],
["cer","191004","fluff - frazione leggera e polveri, diversi da quelli di cui alla voce 19 10 03"],
["cer","191005","*altre frazioni, contenenti sostanze pericolose"],
["cer","191006","altre frazioni, diverse da quelle di cui alla voce 19 10 05"],
["cer","191100","rifiuti prodotti dalla rigenerazione dell'olio"],
["cer","191101","*filtri di argilla esauriti"],
["cer","191102","*catrami acidi"],
["cer","191103","*rifiuti liquidi acquosi"],
["cer","191104","*rifiuti prodotti dalla purificazione di carburanti tramite basi"],
["cer","191105","*fanghi prodotti dal trattamento in loco degli effluenti, contenenti sostanze pericolose"],
["cer","191106","fanghi prodotti dal trattamento in loco degli effluenti, diversi da quelli di cui alla voce 19 11 05"],
["cer","191107","*rifiuti prodotti dalla purificazione dei fumi"],
["cer","191199","rifiuti non specificati altrimenti"],
["cer","191200","rifiuti prodotti dal trattamento meccanico dei rifiuti (ad esempio selezione, triturazione, compattazione, riduzione in pellet) non specificati altrimenti"],
["cer","191201","carta e cartone"],
["cer","191202","metalli ferrosi"],
["cer","191203","metalli non ferrosi"],
["cer","191204","plastica e gomma"],
["cer","191205","vetro"],
["cer","191206","*legno contenente sostanze pericolose"],
["cer","191207","legno diverso da quello di cui alla voce 19 12 06"],
["cer","191208","prodotti tessili"],
["cer","191209","minerali (ad esempio sabbia, rocce)"],
["cer","191210","rifiuti combustibili (combustibile da rifiuti)"],
["cer","191211","*altri rifiuti (compresi materiali misti) prodotti dal trattamento meccanico dei rifiuti, contenenti sostanze pericolose"],
["cer","191212","altri rifiuti (compresi materiali misti) prodotti dal trattamento meccanico dei rifiuti, diversi da quelli di cui alla voce 19 12 11"],
["cer","191300","rifiuti prodotti dalle operazioni di bonifica di terreni e risanamento delle acque di falda"],
["cer","191301","*rifiuti solidi prodotti dalle operazioni di bonifica dei terreni, contenenti sostanze pericolose"],
["cer","191302","rifiuti solidi prodotti dalle operazioni di bonifica dei terreni, diversi da quelli di cui alla voce 19 13 01"],
["cer","191303","*fanghi prodotti dalle operazioni di bonifica dei terreni, contenenti sostanze pericolose"],
["cer","191304","fanghi prodotti dalle operazioni di bonifica dei terreni, diversi da quelli di cui alla voce 19 13 03"],
["cer","191305","*fanghi prodotti dalle operazioni di risanamento delle acque di falda, contenenti sostanze pericolose"],
["cer","191306","fanghi prodotti dalle operazioni di risanamento delle acque di falda, diversi da quelli di cui alla voce 19 13 05"],
["cer","191307","*rifiuti liquidi acquosi e concentrati acquosi prodotti dalle operazioni di risanamento delle acque di falda, contenenti sostanze pericolose"],
["cer","191308","rifiuti liquidi acquosi e concentrati acquosi prodotti dalle operazioni di risanamento delle acque di falda, diversi da quelli di cui alla voce 19 13 07"],
["cer","200000","RIFIUTI URBANI (RIFIUTI DOMESTICI E ASSIMILABILI PRODOTTI DA ATTIVITÀ COMMERCIALI E INDUSTRIALI NONCHÉ DALLE ISTITUZIONI) INCLUSI I RIFIUTI DELLA RACCOLTA DIFFERENZIATA"],
["cer","200100","frazioni oggetto di raccolta differenziata (tranne 15 01)"],
["cer","200101","carta e cartone"],
["cer","200102","vetro"],
["cer","200108","rifiuti biodegradabili di cucine e mense"],
["cer","200110","abbigliamento"],
["cer","200111","prodotti tessili"],
["cer","200113","*solventi"],
["cer","200114","*acidi"],
["cer","200115","*sostanze alcaline"],
["cer","200117","*prodotti fotochimici"],
["cer","200119","*pesticidi"],
["cer","200121","*tubi fluorescenti ed altri rifiuti contenenti mercurio"],
["cer","200123","*apparecchiature fuori uso contenenti clorofluorocarburi"],
["cer","200125","oli e grassi commestibili"],
["cer","200126","*oli e grassi diversi da quelli di cui alla voce 20 01 25"],
["cer","200127","*vernici, inchiostri, adesivi e resine contenenti sostanze pericolose"],
["cer","200128","vernici, inchiostri, adesivi e resine diversi da quelli di cui alla voce 20 01 27"],
["cer","200129","*detergenti contenenti sostanze pericolose"],
["cer","200130","detergenti diversi da quelli di cui alla voce 20 01 29"],
["cer","200131","*medicinali citotossici e citostatici"],
["cer","200132","medicinali diversi da quelli di cui alla voce 20 01 31"],
["cer","200133","*batterie e accumulatori di cui alle voci 16 06 01, 16 06 02 e 16 06 03 nonché batterie e accumulatori non suddivisi contenenti tali batterie"],
["cer","200134","batterie e accumulatori diversi da quelli di cui alla voce 20 01 33"],
["cer","200135","*apparecchiature elettriche ed elettroniche fuori uso, diverse da quelle di cui alla voce 20 01 21 e 20 01 23, contenenti componenti pericolosi (6)"],
["cer","200136","apparecchiature elettriche ed elettroniche fuori uso, diverse da quelle di cui alle voci 20 01 21, 20 01 23 e 20 01 35"],
["cer","200137","*legno, contenente sostanze pericolose"],
["cer","200138","legno, diverso da quello di cui alla voce 20 01 37"],
["cer","200139","plastica"],
["cer","200140","metallo"],
["cer","200141","rifiuti prodotti dalla pulizia di camini e ciminiere"],
["cer","200199","altre frazioni non specificate altrimenti"],
["cer","200200","rifiuti prodotti da giardini e parchi (inclusi i rifiuti provenienti da cimiteri)"],
["cer","200201","rifiuti biodegradabili"],
["cer","200202","terra e roccia"],
["cer","200203","altri rifiuti non biodegradabili"],
["cer","200300","altri rifiuti urbani"],
["cer","200301","rifiuti urbani non differenziati"],
["cer","200302","rifiuti dei mercati"],
["cer","200303","residui della pulizia stradale"],
["cer","200304","fanghi delle fosse settiche"],
["cer","200306","rifiuti della pulizia delle fognature"],
["cer","200307","rifiuti ingombranti"],
["cer","200399","rifiuti urbani non specificati altrimenti"]


		);

		// Loop through each user above and create the record for them in the database
		foreach ($values as $value) {
			lookup::create(array_combine($keys,array_pad($value,count($keys),null)));
		}

		Model::reguard();   
    }
}
